//! Syscalls for arch `arm`.

#![allow(non_camel_case_types)]

// This file is automatically generated. Do not edit.

/// List of system call numbers.
#[repr(usize)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Sysno {
    /// See doc at [restart_syscall(2)](https://man7.org/linux/man-pages/man2/restart_syscall.2.html).
    restart_syscall = 0,
    /// See doc at [exit(2)](https://man7.org/linux/man-pages/man2/exit.2.html).
    exit = 1,
    /// See doc at [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html).
    fork = 2,
    /// See doc at [read(2)](https://man7.org/linux/man-pages/man2/read.2.html).
    read = 3,
    /// See doc at [write(2)](https://man7.org/linux/man-pages/man2/write.2.html).
    write = 4,
    /// See doc at [open(2)](https://man7.org/linux/man-pages/man2/open.2.html).
    open = 5,
    /// See doc at [close(2)](https://man7.org/linux/man-pages/man2/close.2.html).
    close = 6,
    /// See doc at [creat(2)](https://man7.org/linux/man-pages/man2/creat.2.html).
    creat = 8,
    /// See doc at [link(2)](https://man7.org/linux/man-pages/man2/link.2.html).
    link = 9,
    /// See doc at [unlink(2)](https://man7.org/linux/man-pages/man2/unlink.2.html).
    unlink = 10,
    /// See doc at [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html).
    execve = 11,
    /// See doc at [chdir(2)](https://man7.org/linux/man-pages/man2/chdir.2.html).
    chdir = 12,
    /// See doc at [mknod(2)](https://man7.org/linux/man-pages/man2/mknod.2.html).
    mknod = 14,
    /// See doc at [chmod(2)](https://man7.org/linux/man-pages/man2/chmod.2.html).
    chmod = 15,
    /// See doc at [lchown(2)](https://man7.org/linux/man-pages/man2/lchown.2.html).
    lchown = 16,
    /// See doc at [lseek(2)](https://man7.org/linux/man-pages/man2/lseek.2.html).
    lseek = 19,
    /// See doc at [getpid(2)](https://man7.org/linux/man-pages/man2/getpid.2.html).
    getpid = 20,
    /// See doc at [mount(2)](https://man7.org/linux/man-pages/man2/mount.2.html).
    mount = 21,
    /// See doc at [setuid(2)](https://man7.org/linux/man-pages/man2/setuid.2.html).
    setuid = 23,
    /// See doc at [getuid(2)](https://man7.org/linux/man-pages/man2/getuid.2.html).
    getuid = 24,
    /// See doc at [ptrace(2)](https://man7.org/linux/man-pages/man2/ptrace.2.html).
    ptrace = 26,
    /// See doc at [pause(2)](https://man7.org/linux/man-pages/man2/pause.2.html).
    pause = 29,
    /// See doc at [access(2)](https://man7.org/linux/man-pages/man2/access.2.html).
    access = 33,
    /// See doc at [nice(2)](https://man7.org/linux/man-pages/man2/nice.2.html).
    nice = 34,
    /// See doc at [sync(2)](https://man7.org/linux/man-pages/man2/sync.2.html).
    sync = 36,
    /// See doc at [kill(2)](https://man7.org/linux/man-pages/man2/kill.2.html).
    kill = 37,
    /// See doc at [rename(2)](https://man7.org/linux/man-pages/man2/rename.2.html).
    rename = 38,
    /// See doc at [mkdir(2)](https://man7.org/linux/man-pages/man2/mkdir.2.html).
    mkdir = 39,
    /// See doc at [rmdir(2)](https://man7.org/linux/man-pages/man2/rmdir.2.html).
    rmdir = 40,
    /// See doc at [dup(2)](https://man7.org/linux/man-pages/man2/dup.2.html).
    dup = 41,
    /// See doc at [pipe(2)](https://man7.org/linux/man-pages/man2/pipe.2.html).
    pipe = 42,
    /// See doc at [times(2)](https://man7.org/linux/man-pages/man2/times.2.html).
    times = 43,
    /// See doc at [brk(2)](https://man7.org/linux/man-pages/man2/brk.2.html).
    brk = 45,
    /// See doc at [setgid(2)](https://man7.org/linux/man-pages/man2/setgid.2.html).
    setgid = 46,
    /// See doc at [getgid(2)](https://man7.org/linux/man-pages/man2/getgid.2.html).
    getgid = 47,
    /// See doc at [geteuid(2)](https://man7.org/linux/man-pages/man2/geteuid.2.html).
    geteuid = 49,
    /// See doc at [getegid(2)](https://man7.org/linux/man-pages/man2/getegid.2.html).
    getegid = 50,
    /// See doc at [acct(2)](https://man7.org/linux/man-pages/man2/acct.2.html).
    acct = 51,
    /// See doc at [umount2(2)](https://man7.org/linux/man-pages/man2/umount2.2.html).
    umount2 = 52,
    /// See doc at [ioctl(2)](https://man7.org/linux/man-pages/man2/ioctl.2.html).
    ioctl = 54,
    /// See doc at [fcntl(2)](https://man7.org/linux/man-pages/man2/fcntl.2.html).
    fcntl = 55,
    /// See doc at [setpgid(2)](https://man7.org/linux/man-pages/man2/setpgid.2.html).
    setpgid = 57,
    /// See doc at [umask(2)](https://man7.org/linux/man-pages/man2/umask.2.html).
    umask = 60,
    /// See doc at [chroot(2)](https://man7.org/linux/man-pages/man2/chroot.2.html).
    chroot = 61,
    /// See doc at [ustat(2)](https://man7.org/linux/man-pages/man2/ustat.2.html).
    ustat = 62,
    /// See doc at [dup2(2)](https://man7.org/linux/man-pages/man2/dup2.2.html).
    dup2 = 63,
    /// See doc at [getppid(2)](https://man7.org/linux/man-pages/man2/getppid.2.html).
    getppid = 64,
    /// See doc at [getpgrp(2)](https://man7.org/linux/man-pages/man2/getpgrp.2.html).
    getpgrp = 65,
    /// See doc at [setsid(2)](https://man7.org/linux/man-pages/man2/setsid.2.html).
    setsid = 66,
    /// See doc at [sigaction(2)](https://man7.org/linux/man-pages/man2/sigaction.2.html).
    sigaction = 67,
    /// See doc at [setreuid(2)](https://man7.org/linux/man-pages/man2/setreuid.2.html).
    setreuid = 70,
    /// See doc at [setregid(2)](https://man7.org/linux/man-pages/man2/setregid.2.html).
    setregid = 71,
    /// See doc at [sigsuspend(2)](https://man7.org/linux/man-pages/man2/sigsuspend.2.html).
    sigsuspend = 72,
    /// See doc at [sigpending(2)](https://man7.org/linux/man-pages/man2/sigpending.2.html).
    sigpending = 73,
    /// See doc at [sethostname(2)](https://man7.org/linux/man-pages/man2/sethostname.2.html).
    sethostname = 74,
    /// See doc at [setrlimit(2)](https://man7.org/linux/man-pages/man2/setrlimit.2.html).
    setrlimit = 75,
    /// See doc at [getrusage(2)](https://man7.org/linux/man-pages/man2/getrusage.2.html).
    getrusage = 77,
    /// See doc at [gettimeofday(2)](https://man7.org/linux/man-pages/man2/gettimeofday.2.html).
    gettimeofday = 78,
    /// See doc at [settimeofday(2)](https://man7.org/linux/man-pages/man2/settimeofday.2.html).
    settimeofday = 79,
    /// See doc at [getgroups(2)](https://man7.org/linux/man-pages/man2/getgroups.2.html).
    getgroups = 80,
    /// See doc at [setgroups(2)](https://man7.org/linux/man-pages/man2/setgroups.2.html).
    setgroups = 81,
    /// See doc at [symlink(2)](https://man7.org/linux/man-pages/man2/symlink.2.html).
    symlink = 83,
    /// See doc at [readlink(2)](https://man7.org/linux/man-pages/man2/readlink.2.html).
    readlink = 85,
    /// See doc at [uselib(2)](https://man7.org/linux/man-pages/man2/uselib.2.html).
    uselib = 86,
    /// See doc at [swapon(2)](https://man7.org/linux/man-pages/man2/swapon.2.html).
    swapon = 87,
    /// See doc at [reboot(2)](https://man7.org/linux/man-pages/man2/reboot.2.html).
    reboot = 88,
    /// See doc at [munmap(2)](https://man7.org/linux/man-pages/man2/munmap.2.html).
    munmap = 91,
    /// See doc at [truncate(2)](https://man7.org/linux/man-pages/man2/truncate.2.html).
    truncate = 92,
    /// See doc at [ftruncate(2)](https://man7.org/linux/man-pages/man2/ftruncate.2.html).
    ftruncate = 93,
    /// See doc at [fchmod(2)](https://man7.org/linux/man-pages/man2/fchmod.2.html).
    fchmod = 94,
    /// See doc at [fchown(2)](https://man7.org/linux/man-pages/man2/fchown.2.html).
    fchown = 95,
    /// See doc at [getpriority(2)](https://man7.org/linux/man-pages/man2/getpriority.2.html).
    getpriority = 96,
    /// See doc at [setpriority(2)](https://man7.org/linux/man-pages/man2/setpriority.2.html).
    setpriority = 97,
    /// See doc at [statfs(2)](https://man7.org/linux/man-pages/man2/statfs.2.html).
    statfs = 99,
    /// See doc at [fstatfs(2)](https://man7.org/linux/man-pages/man2/fstatfs.2.html).
    fstatfs = 100,
    /// See doc at [syslog(2)](https://man7.org/linux/man-pages/man2/syslog.2.html).
    syslog = 103,
    /// See doc at [setitimer(2)](https://man7.org/linux/man-pages/man2/setitimer.2.html).
    setitimer = 104,
    /// See doc at [getitimer(2)](https://man7.org/linux/man-pages/man2/getitimer.2.html).
    getitimer = 105,
    /// See doc at [stat(2)](https://man7.org/linux/man-pages/man2/stat.2.html).
    stat = 106,
    /// See doc at [lstat(2)](https://man7.org/linux/man-pages/man2/lstat.2.html).
    lstat = 107,
    /// See doc at [fstat(2)](https://man7.org/linux/man-pages/man2/fstat.2.html).
    fstat = 108,
    /// See doc at [vhangup(2)](https://man7.org/linux/man-pages/man2/vhangup.2.html).
    vhangup = 111,
    /// See doc at [wait4(2)](https://man7.org/linux/man-pages/man2/wait4.2.html).
    wait4 = 114,
    /// See doc at [swapoff(2)](https://man7.org/linux/man-pages/man2/swapoff.2.html).
    swapoff = 115,
    /// See doc at [sysinfo(2)](https://man7.org/linux/man-pages/man2/sysinfo.2.html).
    sysinfo = 116,
    /// See doc at [fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html).
    fsync = 118,
    /// See doc at [sigreturn(2)](https://man7.org/linux/man-pages/man2/sigreturn.2.html).
    sigreturn = 119,
    /// See doc at [clone(2)](https://man7.org/linux/man-pages/man2/clone.2.html).
    clone = 120,
    /// See doc at [setdomainname(2)](https://man7.org/linux/man-pages/man2/setdomainname.2.html).
    setdomainname = 121,
    /// See doc at [uname(2)](https://man7.org/linux/man-pages/man2/uname.2.html).
    uname = 122,
    /// See doc at [adjtimex(2)](https://man7.org/linux/man-pages/man2/adjtimex.2.html).
    adjtimex = 124,
    /// See doc at [mprotect(2)](https://man7.org/linux/man-pages/man2/mprotect.2.html).
    mprotect = 125,
    /// See doc at [sigprocmask(2)](https://man7.org/linux/man-pages/man2/sigprocmask.2.html).
    sigprocmask = 126,
    /// See doc at [init_module(2)](https://man7.org/linux/man-pages/man2/init_module.2.html).
    init_module = 128,
    /// See doc at [delete_module(2)](https://man7.org/linux/man-pages/man2/delete_module.2.html).
    delete_module = 129,
    /// See doc at [quotactl(2)](https://man7.org/linux/man-pages/man2/quotactl.2.html).
    quotactl = 131,
    /// See doc at [getpgid(2)](https://man7.org/linux/man-pages/man2/getpgid.2.html).
    getpgid = 132,
    /// See doc at [fchdir(2)](https://man7.org/linux/man-pages/man2/fchdir.2.html).
    fchdir = 133,
    /// See doc at [bdflush(2)](https://man7.org/linux/man-pages/man2/bdflush.2.html).
    bdflush = 134,
    /// See doc at [sysfs(2)](https://man7.org/linux/man-pages/man2/sysfs.2.html).
    sysfs = 135,
    /// See doc at [personality(2)](https://man7.org/linux/man-pages/man2/personality.2.html).
    personality = 136,
    /// See doc at [setfsuid(2)](https://man7.org/linux/man-pages/man2/setfsuid.2.html).
    setfsuid = 138,
    /// See doc at [setfsgid(2)](https://man7.org/linux/man-pages/man2/setfsgid.2.html).
    setfsgid = 139,
    /// See doc at [_llseek(2)](https://man7.org/linux/man-pages/man2/_llseek.2.html).
    _llseek = 140,
    /// See doc at [getdents(2)](https://man7.org/linux/man-pages/man2/getdents.2.html).
    getdents = 141,
    /// See doc at [_newselect(2)](https://man7.org/linux/man-pages/man2/_newselect.2.html).
    _newselect = 142,
    /// See doc at [flock(2)](https://man7.org/linux/man-pages/man2/flock.2.html).
    flock = 143,
    /// See doc at [msync(2)](https://man7.org/linux/man-pages/man2/msync.2.html).
    msync = 144,
    /// See doc at [readv(2)](https://man7.org/linux/man-pages/man2/readv.2.html).
    readv = 145,
    /// See doc at [writev(2)](https://man7.org/linux/man-pages/man2/writev.2.html).
    writev = 146,
    /// See doc at [getsid(2)](https://man7.org/linux/man-pages/man2/getsid.2.html).
    getsid = 147,
    /// See doc at [fdatasync(2)](https://man7.org/linux/man-pages/man2/fdatasync.2.html).
    fdatasync = 148,
    /// See doc at [_sysctl(2)](https://man7.org/linux/man-pages/man2/_sysctl.2.html).
    _sysctl = 149,
    /// See doc at [mlock(2)](https://man7.org/linux/man-pages/man2/mlock.2.html).
    mlock = 150,
    /// See doc at [munlock(2)](https://man7.org/linux/man-pages/man2/munlock.2.html).
    munlock = 151,
    /// See doc at [mlockall(2)](https://man7.org/linux/man-pages/man2/mlockall.2.html).
    mlockall = 152,
    /// See doc at [munlockall(2)](https://man7.org/linux/man-pages/man2/munlockall.2.html).
    munlockall = 153,
    /// See doc at [sched_setparam(2)](https://man7.org/linux/man-pages/man2/sched_setparam.2.html).
    sched_setparam = 154,
    /// See doc at [sched_getparam(2)](https://man7.org/linux/man-pages/man2/sched_getparam.2.html).
    sched_getparam = 155,
    /// See doc at [sched_setscheduler(2)](https://man7.org/linux/man-pages/man2/sched_setscheduler.2.html).
    sched_setscheduler = 156,
    /// See doc at [sched_getscheduler(2)](https://man7.org/linux/man-pages/man2/sched_getscheduler.2.html).
    sched_getscheduler = 157,
    /// See doc at [sched_yield(2)](https://man7.org/linux/man-pages/man2/sched_yield.2.html).
    sched_yield = 158,
    /// See doc at [sched_get_priority_max(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_max.2.html).
    sched_get_priority_max = 159,
    /// See doc at [sched_get_priority_min(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_min.2.html).
    sched_get_priority_min = 160,
    /// See doc at [sched_rr_get_interval(2)](https://man7.org/linux/man-pages/man2/sched_rr_get_interval.2.html).
    sched_rr_get_interval = 161,
    /// See doc at [nanosleep(2)](https://man7.org/linux/man-pages/man2/nanosleep.2.html).
    nanosleep = 162,
    /// See doc at [mremap(2)](https://man7.org/linux/man-pages/man2/mremap.2.html).
    mremap = 163,
    /// See doc at [setresuid(2)](https://man7.org/linux/man-pages/man2/setresuid.2.html).
    setresuid = 164,
    /// See doc at [getresuid(2)](https://man7.org/linux/man-pages/man2/getresuid.2.html).
    getresuid = 165,
    /// See doc at [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html).
    poll = 168,
    /// See doc at [nfsservctl(2)](https://man7.org/linux/man-pages/man2/nfsservctl.2.html).
    nfsservctl = 169,
    /// See doc at [setresgid(2)](https://man7.org/linux/man-pages/man2/setresgid.2.html).
    setresgid = 170,
    /// See doc at [getresgid(2)](https://man7.org/linux/man-pages/man2/getresgid.2.html).
    getresgid = 171,
    /// See doc at [prctl(2)](https://man7.org/linux/man-pages/man2/prctl.2.html).
    prctl = 172,
    /// See doc at [rt_sigreturn(2)](https://man7.org/linux/man-pages/man2/rt_sigreturn.2.html).
    rt_sigreturn = 173,
    /// See doc at [rt_sigaction(2)](https://man7.org/linux/man-pages/man2/rt_sigaction.2.html).
    rt_sigaction = 174,
    /// See doc at [rt_sigprocmask(2)](https://man7.org/linux/man-pages/man2/rt_sigprocmask.2.html).
    rt_sigprocmask = 175,
    /// See doc at [rt_sigpending(2)](https://man7.org/linux/man-pages/man2/rt_sigpending.2.html).
    rt_sigpending = 176,
    /// See doc at [rt_sigtimedwait(2)](https://man7.org/linux/man-pages/man2/rt_sigtimedwait.2.html).
    rt_sigtimedwait = 177,
    /// See doc at [rt_sigqueueinfo(2)](https://man7.org/linux/man-pages/man2/rt_sigqueueinfo.2.html).
    rt_sigqueueinfo = 178,
    /// See doc at [rt_sigsuspend(2)](https://man7.org/linux/man-pages/man2/rt_sigsuspend.2.html).
    rt_sigsuspend = 179,
    /// See doc at [pread64(2)](https://man7.org/linux/man-pages/man2/pread64.2.html).
    pread64 = 180,
    /// See doc at [pwrite64(2)](https://man7.org/linux/man-pages/man2/pwrite64.2.html).
    pwrite64 = 181,
    /// See doc at [chown(2)](https://man7.org/linux/man-pages/man2/chown.2.html).
    chown = 182,
    /// See doc at [getcwd(2)](https://man7.org/linux/man-pages/man2/getcwd.2.html).
    getcwd = 183,
    /// See doc at [capget(2)](https://man7.org/linux/man-pages/man2/capget.2.html).
    capget = 184,
    /// See doc at [capset(2)](https://man7.org/linux/man-pages/man2/capset.2.html).
    capset = 185,
    /// See doc at [sigaltstack(2)](https://man7.org/linux/man-pages/man2/sigaltstack.2.html).
    sigaltstack = 186,
    /// See doc at [sendfile(2)](https://man7.org/linux/man-pages/man2/sendfile.2.html).
    sendfile = 187,
    /// See doc at [vfork(2)](https://man7.org/linux/man-pages/man2/vfork.2.html).
    vfork = 190,
    /// See doc at [ugetrlimit(2)](https://man7.org/linux/man-pages/man2/ugetrlimit.2.html).
    ugetrlimit = 191,
    /// See doc at [mmap2(2)](https://man7.org/linux/man-pages/man2/mmap2.2.html).
    mmap2 = 192,
    /// See doc at [truncate64(2)](https://man7.org/linux/man-pages/man2/truncate64.2.html).
    truncate64 = 193,
    /// See doc at [ftruncate64(2)](https://man7.org/linux/man-pages/man2/ftruncate64.2.html).
    ftruncate64 = 194,
    /// See doc at [stat64(2)](https://man7.org/linux/man-pages/man2/stat64.2.html).
    stat64 = 195,
    /// See doc at [lstat64(2)](https://man7.org/linux/man-pages/man2/lstat64.2.html).
    lstat64 = 196,
    /// See doc at [fstat64(2)](https://man7.org/linux/man-pages/man2/fstat64.2.html).
    fstat64 = 197,
    /// See doc at [lchown32(2)](https://man7.org/linux/man-pages/man2/lchown32.2.html).
    lchown32 = 198,
    /// See doc at [getuid32(2)](https://man7.org/linux/man-pages/man2/getuid32.2.html).
    getuid32 = 199,
    /// See doc at [getgid32(2)](https://man7.org/linux/man-pages/man2/getgid32.2.html).
    getgid32 = 200,
    /// See doc at [geteuid32(2)](https://man7.org/linux/man-pages/man2/geteuid32.2.html).
    geteuid32 = 201,
    /// See doc at [getegid32(2)](https://man7.org/linux/man-pages/man2/getegid32.2.html).
    getegid32 = 202,
    /// See doc at [setreuid32(2)](https://man7.org/linux/man-pages/man2/setreuid32.2.html).
    setreuid32 = 203,
    /// See doc at [setregid32(2)](https://man7.org/linux/man-pages/man2/setregid32.2.html).
    setregid32 = 204,
    /// See doc at [getgroups32(2)](https://man7.org/linux/man-pages/man2/getgroups32.2.html).
    getgroups32 = 205,
    /// See doc at [setgroups32(2)](https://man7.org/linux/man-pages/man2/setgroups32.2.html).
    setgroups32 = 206,
    /// See doc at [fchown32(2)](https://man7.org/linux/man-pages/man2/fchown32.2.html).
    fchown32 = 207,
    /// See doc at [setresuid32(2)](https://man7.org/linux/man-pages/man2/setresuid32.2.html).
    setresuid32 = 208,
    /// See doc at [getresuid32(2)](https://man7.org/linux/man-pages/man2/getresuid32.2.html).
    getresuid32 = 209,
    /// See doc at [setresgid32(2)](https://man7.org/linux/man-pages/man2/setresgid32.2.html).
    setresgid32 = 210,
    /// See doc at [getresgid32(2)](https://man7.org/linux/man-pages/man2/getresgid32.2.html).
    getresgid32 = 211,
    /// See doc at [chown32(2)](https://man7.org/linux/man-pages/man2/chown32.2.html).
    chown32 = 212,
    /// See doc at [setuid32(2)](https://man7.org/linux/man-pages/man2/setuid32.2.html).
    setuid32 = 213,
    /// See doc at [setgid32(2)](https://man7.org/linux/man-pages/man2/setgid32.2.html).
    setgid32 = 214,
    /// See doc at [setfsuid32(2)](https://man7.org/linux/man-pages/man2/setfsuid32.2.html).
    setfsuid32 = 215,
    /// See doc at [setfsgid32(2)](https://man7.org/linux/man-pages/man2/setfsgid32.2.html).
    setfsgid32 = 216,
    /// See doc at [getdents64(2)](https://man7.org/linux/man-pages/man2/getdents64.2.html).
    getdents64 = 217,
    /// See doc at [pivot_root(2)](https://man7.org/linux/man-pages/man2/pivot_root.2.html).
    pivot_root = 218,
    /// See doc at [mincore(2)](https://man7.org/linux/man-pages/man2/mincore.2.html).
    mincore = 219,
    /// See doc at [madvise(2)](https://man7.org/linux/man-pages/man2/madvise.2.html).
    madvise = 220,
    /// See doc at [fcntl64(2)](https://man7.org/linux/man-pages/man2/fcntl64.2.html).
    fcntl64 = 221,
    /// See doc at [gettid(2)](https://man7.org/linux/man-pages/man2/gettid.2.html).
    gettid = 224,
    /// See doc at [readahead(2)](https://man7.org/linux/man-pages/man2/readahead.2.html).
    readahead = 225,
    /// See doc at [setxattr(2)](https://man7.org/linux/man-pages/man2/setxattr.2.html).
    setxattr = 226,
    /// See doc at [lsetxattr(2)](https://man7.org/linux/man-pages/man2/lsetxattr.2.html).
    lsetxattr = 227,
    /// See doc at [fsetxattr(2)](https://man7.org/linux/man-pages/man2/fsetxattr.2.html).
    fsetxattr = 228,
    /// See doc at [getxattr(2)](https://man7.org/linux/man-pages/man2/getxattr.2.html).
    getxattr = 229,
    /// See doc at [lgetxattr(2)](https://man7.org/linux/man-pages/man2/lgetxattr.2.html).
    lgetxattr = 230,
    /// See doc at [fgetxattr(2)](https://man7.org/linux/man-pages/man2/fgetxattr.2.html).
    fgetxattr = 231,
    /// See doc at [listxattr(2)](https://man7.org/linux/man-pages/man2/listxattr.2.html).
    listxattr = 232,
    /// See doc at [llistxattr(2)](https://man7.org/linux/man-pages/man2/llistxattr.2.html).
    llistxattr = 233,
    /// See doc at [flistxattr(2)](https://man7.org/linux/man-pages/man2/flistxattr.2.html).
    flistxattr = 234,
    /// See doc at [removexattr(2)](https://man7.org/linux/man-pages/man2/removexattr.2.html).
    removexattr = 235,
    /// See doc at [lremovexattr(2)](https://man7.org/linux/man-pages/man2/lremovexattr.2.html).
    lremovexattr = 236,
    /// See doc at [fremovexattr(2)](https://man7.org/linux/man-pages/man2/fremovexattr.2.html).
    fremovexattr = 237,
    /// See doc at [tkill(2)](https://man7.org/linux/man-pages/man2/tkill.2.html).
    tkill = 238,
    /// See doc at [sendfile64(2)](https://man7.org/linux/man-pages/man2/sendfile64.2.html).
    sendfile64 = 239,
    /// See doc at [futex(2)](https://man7.org/linux/man-pages/man2/futex.2.html).
    futex = 240,
    /// See doc at [sched_setaffinity(2)](https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html).
    sched_setaffinity = 241,
    /// See doc at [sched_getaffinity(2)](https://man7.org/linux/man-pages/man2/sched_getaffinity.2.html).
    sched_getaffinity = 242,
    /// See doc at [io_setup(2)](https://man7.org/linux/man-pages/man2/io_setup.2.html).
    io_setup = 243,
    /// See doc at [io_destroy(2)](https://man7.org/linux/man-pages/man2/io_destroy.2.html).
    io_destroy = 244,
    /// See doc at [io_getevents(2)](https://man7.org/linux/man-pages/man2/io_getevents.2.html).
    io_getevents = 245,
    /// See doc at [io_submit(2)](https://man7.org/linux/man-pages/man2/io_submit.2.html).
    io_submit = 246,
    /// See doc at [io_cancel(2)](https://man7.org/linux/man-pages/man2/io_cancel.2.html).
    io_cancel = 247,
    /// See doc at [exit_group(2)](https://man7.org/linux/man-pages/man2/exit_group.2.html).
    exit_group = 248,
    /// See doc at [lookup_dcookie(2)](https://man7.org/linux/man-pages/man2/lookup_dcookie.2.html).
    lookup_dcookie = 249,
    /// See doc at [epoll_create(2)](https://man7.org/linux/man-pages/man2/epoll_create.2.html).
    epoll_create = 250,
    /// See doc at [epoll_ctl(2)](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html).
    epoll_ctl = 251,
    /// See doc at [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html).
    epoll_wait = 252,
    /// See doc at [remap_file_pages(2)](https://man7.org/linux/man-pages/man2/remap_file_pages.2.html).
    remap_file_pages = 253,
    /// See doc at [set_tid_address(2)](https://man7.org/linux/man-pages/man2/set_tid_address.2.html).
    set_tid_address = 256,
    /// See doc at [timer_create(2)](https://man7.org/linux/man-pages/man2/timer_create.2.html).
    timer_create = 257,
    /// See doc at [timer_settime(2)](https://man7.org/linux/man-pages/man2/timer_settime.2.html).
    timer_settime = 258,
    /// See doc at [timer_gettime(2)](https://man7.org/linux/man-pages/man2/timer_gettime.2.html).
    timer_gettime = 259,
    /// See doc at [timer_getoverrun(2)](https://man7.org/linux/man-pages/man2/timer_getoverrun.2.html).
    timer_getoverrun = 260,
    /// See doc at [timer_delete(2)](https://man7.org/linux/man-pages/man2/timer_delete.2.html).
    timer_delete = 261,
    /// See doc at [clock_settime(2)](https://man7.org/linux/man-pages/man2/clock_settime.2.html).
    clock_settime = 262,
    /// See doc at [clock_gettime(2)](https://man7.org/linux/man-pages/man2/clock_gettime.2.html).
    clock_gettime = 263,
    /// See doc at [clock_getres(2)](https://man7.org/linux/man-pages/man2/clock_getres.2.html).
    clock_getres = 264,
    /// See doc at [clock_nanosleep(2)](https://man7.org/linux/man-pages/man2/clock_nanosleep.2.html).
    clock_nanosleep = 265,
    /// See doc at [statfs64(2)](https://man7.org/linux/man-pages/man2/statfs64.2.html).
    statfs64 = 266,
    /// See doc at [fstatfs64(2)](https://man7.org/linux/man-pages/man2/fstatfs64.2.html).
    fstatfs64 = 267,
    /// See doc at [tgkill(2)](https://man7.org/linux/man-pages/man2/tgkill.2.html).
    tgkill = 268,
    /// See doc at [utimes(2)](https://man7.org/linux/man-pages/man2/utimes.2.html).
    utimes = 269,
    /// See doc at [arm_fadvise64_64(2)](https://man7.org/linux/man-pages/man2/arm_fadvise64_64.2.html).
    arm_fadvise64_64 = 270,
    /// See doc at [pciconfig_iobase(2)](https://man7.org/linux/man-pages/man2/pciconfig_iobase.2.html).
    pciconfig_iobase = 271,
    /// See doc at [pciconfig_read(2)](https://man7.org/linux/man-pages/man2/pciconfig_read.2.html).
    pciconfig_read = 272,
    /// See doc at [pciconfig_write(2)](https://man7.org/linux/man-pages/man2/pciconfig_write.2.html).
    pciconfig_write = 273,
    /// See doc at [mq_open(2)](https://man7.org/linux/man-pages/man2/mq_open.2.html).
    mq_open = 274,
    /// See doc at [mq_unlink(2)](https://man7.org/linux/man-pages/man2/mq_unlink.2.html).
    mq_unlink = 275,
    /// See doc at [mq_timedsend(2)](https://man7.org/linux/man-pages/man2/mq_timedsend.2.html).
    mq_timedsend = 276,
    /// See doc at [mq_timedreceive(2)](https://man7.org/linux/man-pages/man2/mq_timedreceive.2.html).
    mq_timedreceive = 277,
    /// See doc at [mq_notify(2)](https://man7.org/linux/man-pages/man2/mq_notify.2.html).
    mq_notify = 278,
    /// See doc at [mq_getsetattr(2)](https://man7.org/linux/man-pages/man2/mq_getsetattr.2.html).
    mq_getsetattr = 279,
    /// See doc at [waitid(2)](https://man7.org/linux/man-pages/man2/waitid.2.html).
    waitid = 280,
    /// See doc at [socket(2)](https://man7.org/linux/man-pages/man2/socket.2.html).
    socket = 281,
    /// See doc at [bind(2)](https://man7.org/linux/man-pages/man2/bind.2.html).
    bind = 282,
    /// See doc at [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html).
    connect = 283,
    /// See doc at [listen(2)](https://man7.org/linux/man-pages/man2/listen.2.html).
    listen = 284,
    /// See doc at [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html).
    accept = 285,
    /// See doc at [getsockname(2)](https://man7.org/linux/man-pages/man2/getsockname.2.html).
    getsockname = 286,
    /// See doc at [getpeername(2)](https://man7.org/linux/man-pages/man2/getpeername.2.html).
    getpeername = 287,
    /// See doc at [socketpair(2)](https://man7.org/linux/man-pages/man2/socketpair.2.html).
    socketpair = 288,
    /// See doc at [send(2)](https://man7.org/linux/man-pages/man2/send.2.html).
    send = 289,
    /// See doc at [sendto(2)](https://man7.org/linux/man-pages/man2/sendto.2.html).
    sendto = 290,
    /// See doc at [recv(2)](https://man7.org/linux/man-pages/man2/recv.2.html).
    recv = 291,
    /// See doc at [recvfrom(2)](https://man7.org/linux/man-pages/man2/recvfrom.2.html).
    recvfrom = 292,
    /// See doc at [shutdown(2)](https://man7.org/linux/man-pages/man2/shutdown.2.html).
    shutdown = 293,
    /// See doc at [setsockopt(2)](https://man7.org/linux/man-pages/man2/setsockopt.2.html).
    setsockopt = 294,
    /// See doc at [getsockopt(2)](https://man7.org/linux/man-pages/man2/getsockopt.2.html).
    getsockopt = 295,
    /// See doc at [sendmsg(2)](https://man7.org/linux/man-pages/man2/sendmsg.2.html).
    sendmsg = 296,
    /// See doc at [recvmsg(2)](https://man7.org/linux/man-pages/man2/recvmsg.2.html).
    recvmsg = 297,
    /// See doc at [semop(2)](https://man7.org/linux/man-pages/man2/semop.2.html).
    semop = 298,
    /// See doc at [semget(2)](https://man7.org/linux/man-pages/man2/semget.2.html).
    semget = 299,
    /// See doc at [semctl(2)](https://man7.org/linux/man-pages/man2/semctl.2.html).
    semctl = 300,
    /// See doc at [msgsnd(2)](https://man7.org/linux/man-pages/man2/msgsnd.2.html).
    msgsnd = 301,
    /// See doc at [msgrcv(2)](https://man7.org/linux/man-pages/man2/msgrcv.2.html).
    msgrcv = 302,
    /// See doc at [msgget(2)](https://man7.org/linux/man-pages/man2/msgget.2.html).
    msgget = 303,
    /// See doc at [msgctl(2)](https://man7.org/linux/man-pages/man2/msgctl.2.html).
    msgctl = 304,
    /// See doc at [shmat(2)](https://man7.org/linux/man-pages/man2/shmat.2.html).
    shmat = 305,
    /// See doc at [shmdt(2)](https://man7.org/linux/man-pages/man2/shmdt.2.html).
    shmdt = 306,
    /// See doc at [shmget(2)](https://man7.org/linux/man-pages/man2/shmget.2.html).
    shmget = 307,
    /// See doc at [shmctl(2)](https://man7.org/linux/man-pages/man2/shmctl.2.html).
    shmctl = 308,
    /// See doc at [add_key(2)](https://man7.org/linux/man-pages/man2/add_key.2.html).
    add_key = 309,
    /// See doc at [request_key(2)](https://man7.org/linux/man-pages/man2/request_key.2.html).
    request_key = 310,
    /// See doc at [keyctl(2)](https://man7.org/linux/man-pages/man2/keyctl.2.html).
    keyctl = 311,
    /// See doc at [semtimedop(2)](https://man7.org/linux/man-pages/man2/semtimedop.2.html).
    semtimedop = 312,
    /// See doc at [vserver(2)](https://man7.org/linux/man-pages/man2/vserver.2.html).
    vserver = 313,
    /// See doc at [ioprio_set(2)](https://man7.org/linux/man-pages/man2/ioprio_set.2.html).
    ioprio_set = 314,
    /// See doc at [ioprio_get(2)](https://man7.org/linux/man-pages/man2/ioprio_get.2.html).
    ioprio_get = 315,
    /// See doc at [inotify_init(2)](https://man7.org/linux/man-pages/man2/inotify_init.2.html).
    inotify_init = 316,
    /// See doc at [inotify_add_watch(2)](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html).
    inotify_add_watch = 317,
    /// See doc at [inotify_rm_watch(2)](https://man7.org/linux/man-pages/man2/inotify_rm_watch.2.html).
    inotify_rm_watch = 318,
    /// See doc at [mbind(2)](https://man7.org/linux/man-pages/man2/mbind.2.html).
    mbind = 319,
    /// See doc at [get_mempolicy(2)](https://man7.org/linux/man-pages/man2/get_mempolicy.2.html).
    get_mempolicy = 320,
    /// See doc at [set_mempolicy(2)](https://man7.org/linux/man-pages/man2/set_mempolicy.2.html).
    set_mempolicy = 321,
    /// See doc at [openat(2)](https://man7.org/linux/man-pages/man2/openat.2.html).
    openat = 322,
    /// See doc at [mkdirat(2)](https://man7.org/linux/man-pages/man2/mkdirat.2.html).
    mkdirat = 323,
    /// See doc at [mknodat(2)](https://man7.org/linux/man-pages/man2/mknodat.2.html).
    mknodat = 324,
    /// See doc at [fchownat(2)](https://man7.org/linux/man-pages/man2/fchownat.2.html).
    fchownat = 325,
    /// See doc at [futimesat(2)](https://man7.org/linux/man-pages/man2/futimesat.2.html).
    futimesat = 326,
    /// See doc at [fstatat64(2)](https://man7.org/linux/man-pages/man2/fstatat64.2.html).
    fstatat64 = 327,
    /// See doc at [unlinkat(2)](https://man7.org/linux/man-pages/man2/unlinkat.2.html).
    unlinkat = 328,
    /// See doc at [renameat(2)](https://man7.org/linux/man-pages/man2/renameat.2.html).
    renameat = 329,
    /// See doc at [linkat(2)](https://man7.org/linux/man-pages/man2/linkat.2.html).
    linkat = 330,
    /// See doc at [symlinkat(2)](https://man7.org/linux/man-pages/man2/symlinkat.2.html).
    symlinkat = 331,
    /// See doc at [readlinkat(2)](https://man7.org/linux/man-pages/man2/readlinkat.2.html).
    readlinkat = 332,
    /// See doc at [fchmodat(2)](https://man7.org/linux/man-pages/man2/fchmodat.2.html).
    fchmodat = 333,
    /// See doc at [faccessat(2)](https://man7.org/linux/man-pages/man2/faccessat.2.html).
    faccessat = 334,
    /// See doc at [pselect6(2)](https://man7.org/linux/man-pages/man2/pselect6.2.html).
    pselect6 = 335,
    /// See doc at [ppoll(2)](https://man7.org/linux/man-pages/man2/ppoll.2.html).
    ppoll = 336,
    /// See doc at [unshare(2)](https://man7.org/linux/man-pages/man2/unshare.2.html).
    unshare = 337,
    /// See doc at [set_robust_list(2)](https://man7.org/linux/man-pages/man2/set_robust_list.2.html).
    set_robust_list = 338,
    /// See doc at [get_robust_list(2)](https://man7.org/linux/man-pages/man2/get_robust_list.2.html).
    get_robust_list = 339,
    /// See doc at [splice(2)](https://man7.org/linux/man-pages/man2/splice.2.html).
    splice = 340,
    /// See doc at [arm_sync_file_range(2)](https://man7.org/linux/man-pages/man2/arm_sync_file_range.2.html).
    arm_sync_file_range = 341,
    /// See doc at [tee(2)](https://man7.org/linux/man-pages/man2/tee.2.html).
    tee = 342,
    /// See doc at [vmsplice(2)](https://man7.org/linux/man-pages/man2/vmsplice.2.html).
    vmsplice = 343,
    /// See doc at [move_pages(2)](https://man7.org/linux/man-pages/man2/move_pages.2.html).
    move_pages = 344,
    /// See doc at [getcpu(2)](https://man7.org/linux/man-pages/man2/getcpu.2.html).
    getcpu = 345,
    /// See doc at [epoll_pwait(2)](https://man7.org/linux/man-pages/man2/epoll_pwait.2.html).
    epoll_pwait = 346,
    /// See doc at [kexec_load(2)](https://man7.org/linux/man-pages/man2/kexec_load.2.html).
    kexec_load = 347,
    /// See doc at [utimensat(2)](https://man7.org/linux/man-pages/man2/utimensat.2.html).
    utimensat = 348,
    /// See doc at [signalfd(2)](https://man7.org/linux/man-pages/man2/signalfd.2.html).
    signalfd = 349,
    /// See doc at [timerfd_create(2)](https://man7.org/linux/man-pages/man2/timerfd_create.2.html).
    timerfd_create = 350,
    /// See doc at [eventfd(2)](https://man7.org/linux/man-pages/man2/eventfd.2.html).
    eventfd = 351,
    /// See doc at [fallocate(2)](https://man7.org/linux/man-pages/man2/fallocate.2.html).
    fallocate = 352,
    /// See doc at [timerfd_settime(2)](https://man7.org/linux/man-pages/man2/timerfd_settime.2.html).
    timerfd_settime = 353,
    /// See doc at [timerfd_gettime(2)](https://man7.org/linux/man-pages/man2/timerfd_gettime.2.html).
    timerfd_gettime = 354,
    /// See doc at [signalfd4(2)](https://man7.org/linux/man-pages/man2/signalfd4.2.html).
    signalfd4 = 355,
    /// See doc at [eventfd2(2)](https://man7.org/linux/man-pages/man2/eventfd2.2.html).
    eventfd2 = 356,
    /// See doc at [epoll_create1(2)](https://man7.org/linux/man-pages/man2/epoll_create1.2.html).
    epoll_create1 = 357,
    /// See doc at [dup3(2)](https://man7.org/linux/man-pages/man2/dup3.2.html).
    dup3 = 358,
    /// See doc at [pipe2(2)](https://man7.org/linux/man-pages/man2/pipe2.2.html).
    pipe2 = 359,
    /// See doc at [inotify_init1(2)](https://man7.org/linux/man-pages/man2/inotify_init1.2.html).
    inotify_init1 = 360,
    /// See doc at [preadv(2)](https://man7.org/linux/man-pages/man2/preadv.2.html).
    preadv = 361,
    /// See doc at [pwritev(2)](https://man7.org/linux/man-pages/man2/pwritev.2.html).
    pwritev = 362,
    /// See doc at [rt_tgsigqueueinfo(2)](https://man7.org/linux/man-pages/man2/rt_tgsigqueueinfo.2.html).
    rt_tgsigqueueinfo = 363,
    /// See doc at [perf_event_open(2)](https://man7.org/linux/man-pages/man2/perf_event_open.2.html).
    perf_event_open = 364,
    /// See doc at [recvmmsg(2)](https://man7.org/linux/man-pages/man2/recvmmsg.2.html).
    recvmmsg = 365,
    /// See doc at [accept4(2)](https://man7.org/linux/man-pages/man2/accept4.2.html).
    accept4 = 366,
    /// See doc at [fanotify_init(2)](https://man7.org/linux/man-pages/man2/fanotify_init.2.html).
    fanotify_init = 367,
    /// See doc at [fanotify_mark(2)](https://man7.org/linux/man-pages/man2/fanotify_mark.2.html).
    fanotify_mark = 368,
    /// See doc at [prlimit64(2)](https://man7.org/linux/man-pages/man2/prlimit64.2.html).
    prlimit64 = 369,
    /// See doc at [name_to_handle_at(2)](https://man7.org/linux/man-pages/man2/name_to_handle_at.2.html).
    name_to_handle_at = 370,
    /// See doc at [open_by_handle_at(2)](https://man7.org/linux/man-pages/man2/open_by_handle_at.2.html).
    open_by_handle_at = 371,
    /// See doc at [clock_adjtime(2)](https://man7.org/linux/man-pages/man2/clock_adjtime.2.html).
    clock_adjtime = 372,
    /// See doc at [syncfs(2)](https://man7.org/linux/man-pages/man2/syncfs.2.html).
    syncfs = 373,
    /// See doc at [sendmmsg(2)](https://man7.org/linux/man-pages/man2/sendmmsg.2.html).
    sendmmsg = 374,
    /// See doc at [setns(2)](https://man7.org/linux/man-pages/man2/setns.2.html).
    setns = 375,
    /// See doc at [process_vm_readv(2)](https://man7.org/linux/man-pages/man2/process_vm_readv.2.html).
    process_vm_readv = 376,
    /// See doc at [process_vm_writev(2)](https://man7.org/linux/man-pages/man2/process_vm_writev.2.html).
    process_vm_writev = 377,
    /// See doc at [kcmp(2)](https://man7.org/linux/man-pages/man2/kcmp.2.html).
    kcmp = 378,
    /// See doc at [finit_module(2)](https://man7.org/linux/man-pages/man2/finit_module.2.html).
    finit_module = 379,
    /// See doc at [sched_setattr(2)](https://man7.org/linux/man-pages/man2/sched_setattr.2.html).
    sched_setattr = 380,
    /// See doc at [sched_getattr(2)](https://man7.org/linux/man-pages/man2/sched_getattr.2.html).
    sched_getattr = 381,
    /// See doc at [renameat2(2)](https://man7.org/linux/man-pages/man2/renameat2.2.html).
    renameat2 = 382,
    /// See doc at [seccomp(2)](https://man7.org/linux/man-pages/man2/seccomp.2.html).
    seccomp = 383,
    /// See doc at [getrandom(2)](https://man7.org/linux/man-pages/man2/getrandom.2.html).
    getrandom = 384,
    /// See doc at [memfd_create(2)](https://man7.org/linux/man-pages/man2/memfd_create.2.html).
    memfd_create = 385,
    /// See doc at [bpf(2)](https://man7.org/linux/man-pages/man2/bpf.2.html).
    bpf = 386,
    /// See doc at [execveat(2)](https://man7.org/linux/man-pages/man2/execveat.2.html).
    execveat = 387,
    /// See doc at [userfaultfd(2)](https://man7.org/linux/man-pages/man2/userfaultfd.2.html).
    userfaultfd = 388,
    /// See doc at [membarrier(2)](https://man7.org/linux/man-pages/man2/membarrier.2.html).
    membarrier = 389,
    /// See doc at [mlock2(2)](https://man7.org/linux/man-pages/man2/mlock2.2.html).
    mlock2 = 390,
    /// See doc at [copy_file_range(2)](https://man7.org/linux/man-pages/man2/copy_file_range.2.html).
    copy_file_range = 391,
    /// See doc at [preadv2(2)](https://man7.org/linux/man-pages/man2/preadv2.2.html).
    preadv2 = 392,
    /// See doc at [pwritev2(2)](https://man7.org/linux/man-pages/man2/pwritev2.2.html).
    pwritev2 = 393,
    /// See doc at [pkey_mprotect(2)](https://man7.org/linux/man-pages/man2/pkey_mprotect.2.html).
    pkey_mprotect = 394,
    /// See doc at [pkey_alloc(2)](https://man7.org/linux/man-pages/man2/pkey_alloc.2.html).
    pkey_alloc = 395,
    /// See doc at [pkey_free(2)](https://man7.org/linux/man-pages/man2/pkey_free.2.html).
    pkey_free = 396,
    /// See doc at [statx(2)](https://man7.org/linux/man-pages/man2/statx.2.html).
    statx = 397,
    /// See doc at [rseq(2)](https://man7.org/linux/man-pages/man2/rseq.2.html).
    rseq = 398,
    /// See doc at [io_pgetevents(2)](https://man7.org/linux/man-pages/man2/io_pgetevents.2.html).
    io_pgetevents = 399,
    /// See doc at [migrate_pages(2)](https://man7.org/linux/man-pages/man2/migrate_pages.2.html).
    migrate_pages = 400,
    /// See doc at [kexec_file_load(2)](https://man7.org/linux/man-pages/man2/kexec_file_load.2.html).
    kexec_file_load = 401,
    /// See doc at [clock_gettime64(2)](https://man7.org/linux/man-pages/man2/clock_gettime64.2.html).
    clock_gettime64 = 403,
    /// See doc at [clock_settime64(2)](https://man7.org/linux/man-pages/man2/clock_settime64.2.html).
    clock_settime64 = 404,
    /// See doc at [clock_adjtime64(2)](https://man7.org/linux/man-pages/man2/clock_adjtime64.2.html).
    clock_adjtime64 = 405,
    /// See doc at [clock_getres_time64(2)](https://man7.org/linux/man-pages/man2/clock_getres_time64.2.html).
    clock_getres_time64 = 406,
    /// See doc at [clock_nanosleep_time64(2)](https://man7.org/linux/man-pages/man2/clock_nanosleep_time64.2.html).
    clock_nanosleep_time64 = 407,
    /// See doc at [timer_gettime64(2)](https://man7.org/linux/man-pages/man2/timer_gettime64.2.html).
    timer_gettime64 = 408,
    /// See doc at [timer_settime64(2)](https://man7.org/linux/man-pages/man2/timer_settime64.2.html).
    timer_settime64 = 409,
    /// See doc at [timerfd_gettime64(2)](https://man7.org/linux/man-pages/man2/timerfd_gettime64.2.html).
    timerfd_gettime64 = 410,
    /// See doc at [timerfd_settime64(2)](https://man7.org/linux/man-pages/man2/timerfd_settime64.2.html).
    timerfd_settime64 = 411,
    /// See doc at [utimensat_time64(2)](https://man7.org/linux/man-pages/man2/utimensat_time64.2.html).
    utimensat_time64 = 412,
    /// See doc at [pselect6_time64(2)](https://man7.org/linux/man-pages/man2/pselect6_time64.2.html).
    pselect6_time64 = 413,
    /// See doc at [ppoll_time64(2)](https://man7.org/linux/man-pages/man2/ppoll_time64.2.html).
    ppoll_time64 = 414,
    /// See doc at [io_pgetevents_time64(2)](https://man7.org/linux/man-pages/man2/io_pgetevents_time64.2.html).
    io_pgetevents_time64 = 416,
    /// See doc at [recvmmsg_time64(2)](https://man7.org/linux/man-pages/man2/recvmmsg_time64.2.html).
    recvmmsg_time64 = 417,
    /// See doc at [mq_timedsend_time64(2)](https://man7.org/linux/man-pages/man2/mq_timedsend_time64.2.html).
    mq_timedsend_time64 = 418,
    /// See doc at [mq_timedreceive_time64(2)](https://man7.org/linux/man-pages/man2/mq_timedreceive_time64.2.html).
    mq_timedreceive_time64 = 419,
    /// See doc at [semtimedop_time64(2)](https://man7.org/linux/man-pages/man2/semtimedop_time64.2.html).
    semtimedop_time64 = 420,
    /// See doc at [rt_sigtimedwait_time64(2)](https://man7.org/linux/man-pages/man2/rt_sigtimedwait_time64.2.html).
    rt_sigtimedwait_time64 = 421,
    /// See doc at [futex_time64(2)](https://man7.org/linux/man-pages/man2/futex_time64.2.html).
    futex_time64 = 422,
    /// See doc at [sched_rr_get_interval_time64(2)](https://man7.org/linux/man-pages/man2/sched_rr_get_interval_time64.2.html).
    sched_rr_get_interval_time64 = 423,
    /// See doc at [pidfd_send_signal(2)](https://man7.org/linux/man-pages/man2/pidfd_send_signal.2.html).
    pidfd_send_signal = 424,
    /// See doc at [io_uring_setup(2)](https://man7.org/linux/man-pages/man2/io_uring_setup.2.html).
    io_uring_setup = 425,
    /// See doc at [io_uring_enter(2)](https://man7.org/linux/man-pages/man2/io_uring_enter.2.html).
    io_uring_enter = 426,
    /// See doc at [io_uring_register(2)](https://man7.org/linux/man-pages/man2/io_uring_register.2.html).
    io_uring_register = 427,
    /// See doc at [open_tree(2)](https://man7.org/linux/man-pages/man2/open_tree.2.html).
    open_tree = 428,
    /// See doc at [move_mount(2)](https://man7.org/linux/man-pages/man2/move_mount.2.html).
    move_mount = 429,
    /// See doc at [fsopen(2)](https://man7.org/linux/man-pages/man2/fsopen.2.html).
    fsopen = 430,
    /// See doc at [fsconfig(2)](https://man7.org/linux/man-pages/man2/fsconfig.2.html).
    fsconfig = 431,
    /// See doc at [fsmount(2)](https://man7.org/linux/man-pages/man2/fsmount.2.html).
    fsmount = 432,
    /// See doc at [fspick(2)](https://man7.org/linux/man-pages/man2/fspick.2.html).
    fspick = 433,
    /// See doc at [pidfd_open(2)](https://man7.org/linux/man-pages/man2/pidfd_open.2.html).
    pidfd_open = 434,
    /// See doc at [clone3(2)](https://man7.org/linux/man-pages/man2/clone3.2.html).
    clone3 = 435,
    /// See doc at [close_range(2)](https://man7.org/linux/man-pages/man2/close_range.2.html).
    close_range = 436,
    /// See doc at [openat2(2)](https://man7.org/linux/man-pages/man2/openat2.2.html).
    openat2 = 437,
    /// See doc at [pidfd_getfd(2)](https://man7.org/linux/man-pages/man2/pidfd_getfd.2.html).
    pidfd_getfd = 438,
    /// See doc at [faccessat2(2)](https://man7.org/linux/man-pages/man2/faccessat2.2.html).
    faccessat2 = 439,
    /// See doc at [process_madvise(2)](https://man7.org/linux/man-pages/man2/process_madvise.2.html).
    process_madvise = 440,
    /// See doc at [epoll_pwait2(2)](https://man7.org/linux/man-pages/man2/epoll_pwait2.2.html).
    epoll_pwait2 = 441,
    /// See doc at [mount_setattr(2)](https://man7.org/linux/man-pages/man2/mount_setattr.2.html).
    mount_setattr = 442,
    /// See doc at [quotactl_fd(2)](https://man7.org/linux/man-pages/man2/quotactl_fd.2.html).
    quotactl_fd = 443,
    /// See doc at [landlock_create_ruleset(2)](https://man7.org/linux/man-pages/man2/landlock_create_ruleset.2.html).
    landlock_create_ruleset = 444,
    /// See doc at [landlock_add_rule(2)](https://man7.org/linux/man-pages/man2/landlock_add_rule.2.html).
    landlock_add_rule = 445,
    /// See doc at [landlock_restrict_self(2)](https://man7.org/linux/man-pages/man2/landlock_restrict_self.2.html).
    landlock_restrict_self = 446,
    /// See doc at [process_mrelease(2)](https://man7.org/linux/man-pages/man2/process_mrelease.2.html).
    process_mrelease = 448,
    /// See doc at [futex_waitv(2)](https://man7.org/linux/man-pages/man2/futex_waitv.2.html).
    futex_waitv = 449,
    /// See doc at [set_mempolicy_home_node(2)](https://man7.org/linux/man-pages/man2/set_mempolicy_home_node.2.html).
    set_mempolicy_home_node = 450,
    /// See doc at [cachestat(2)](https://man7.org/linux/man-pages/man2/cachestat.2.html).
    cachestat = 451,
    /// See doc at [fchmodat2(2)](https://man7.org/linux/man-pages/man2/fchmodat2.2.html).
    fchmodat2 = 452,
    /// See doc at [map_shadow_stack(2)](https://man7.org/linux/man-pages/man2/map_shadow_stack.2.html).
    map_shadow_stack = 453,
    /// See doc at [futex_wake(2)](https://man7.org/linux/man-pages/man2/futex_wake.2.html).
    futex_wake = 454,
    /// See doc at [futex_wait(2)](https://man7.org/linux/man-pages/man2/futex_wait.2.html).
    futex_wait = 455,
    /// See doc at [futex_requeue(2)](https://man7.org/linux/man-pages/man2/futex_requeue.2.html).
    futex_requeue = 456,
    /// See doc at [statmount(2)](https://man7.org/linux/man-pages/man2/statmount.2.html).
    statmount = 457,
    /// See doc at [listmount(2)](https://man7.org/linux/man-pages/man2/listmount.2.html).
    listmount = 458,
    /// See doc at [lsm_get_self_attr(2)](https://man7.org/linux/man-pages/man2/lsm_get_self_attr.2.html).
    lsm_get_self_attr = 459,
    /// See doc at [lsm_set_self_attr(2)](https://man7.org/linux/man-pages/man2/lsm_set_self_attr.2.html).
    lsm_set_self_attr = 460,
    /// See doc at [lsm_list_modules(2)](https://man7.org/linux/man-pages/man2/lsm_list_modules.2.html).
    lsm_list_modules = 461,
    /// See doc at [mseal(2)](https://man7.org/linux/man-pages/man2/mseal.2.html).
    mseal = 462,
    /// See doc at [setxattrat(2)](https://man7.org/linux/man-pages/man2/setxattrat.2.html).
    setxattrat = 463,
    /// See doc at [getxattrat(2)](https://man7.org/linux/man-pages/man2/getxattrat.2.html).
    getxattrat = 464,
    /// See doc at [listxattrat(2)](https://man7.org/linux/man-pages/man2/listxattrat.2.html).
    listxattrat = 465,
    /// See doc at [removexattrat(2)](https://man7.org/linux/man-pages/man2/removexattrat.2.html).
    removexattrat = 466,
    /// See doc at [open_tree_attr(2)](https://man7.org/linux/man-pages/man2/open_tree_attr.2.html).
    open_tree_attr = 467,
    /// See doc at [file_getattr(2)](https://man7.org/linux/man-pages/man2/file_getattr.2.html).
    file_getattr = 468,
    /// See doc at [file_setattr(2)](https://man7.org/linux/man-pages/man2/file_setattr.2.html).
    file_setattr = 469,
    /// See doc at [breakpoint(2)](https://man7.org/linux/man-pages/man2/breakpoint.2.html).
    breakpoint = 983041,
    /// See doc at [cacheflush(2)](https://man7.org/linux/man-pages/man2/cacheflush.2.html).
    cacheflush = 983042,
    /// See doc at [usr26(2)](https://man7.org/linux/man-pages/man2/usr26.2.html).
    usr26 = 983043,
    /// See doc at [usr32(2)](https://man7.org/linux/man-pages/man2/usr32.2.html).
    usr32 = 983044,
    /// See doc at [set_tls(2)](https://man7.org/linux/man-pages/man2/set_tls.2.html).
    set_tls = 983045,
    /// See doc at [get_tls(2)](https://man7.org/linux/man-pages/man2/get_tls.2.html).
    get_tls = 983046,
}
