//! Syscalls for arch `mips`.

#![allow(non_camel_case_types)]

// This file is automatically generated. Do not edit.

/// List of system call numbers.
#[repr(usize)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Sysno {
    /// See doc at [syscall(2)](https://man7.org/linux/man-pages/man2/syscall.2.html).
    syscall = 4000,
    /// See doc at [exit(2)](https://man7.org/linux/man-pages/man2/exit.2.html).
    exit = 4001,
    /// See doc at [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html).
    fork = 4002,
    /// See doc at [read(2)](https://man7.org/linux/man-pages/man2/read.2.html).
    read = 4003,
    /// See doc at [write(2)](https://man7.org/linux/man-pages/man2/write.2.html).
    write = 4004,
    /// See doc at [open(2)](https://man7.org/linux/man-pages/man2/open.2.html).
    open = 4005,
    /// See doc at [close(2)](https://man7.org/linux/man-pages/man2/close.2.html).
    close = 4006,
    /// See doc at [waitpid(2)](https://man7.org/linux/man-pages/man2/waitpid.2.html).
    waitpid = 4007,
    /// See doc at [creat(2)](https://man7.org/linux/man-pages/man2/creat.2.html).
    creat = 4008,
    /// See doc at [link(2)](https://man7.org/linux/man-pages/man2/link.2.html).
    link = 4009,
    /// See doc at [unlink(2)](https://man7.org/linux/man-pages/man2/unlink.2.html).
    unlink = 4010,
    /// See doc at [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html).
    execve = 4011,
    /// See doc at [chdir(2)](https://man7.org/linux/man-pages/man2/chdir.2.html).
    chdir = 4012,
    /// See doc at [time(2)](https://man7.org/linux/man-pages/man2/time.2.html).
    time = 4013,
    /// See doc at [mknod(2)](https://man7.org/linux/man-pages/man2/mknod.2.html).
    mknod = 4014,
    /// See doc at [chmod(2)](https://man7.org/linux/man-pages/man2/chmod.2.html).
    chmod = 4015,
    /// See doc at [lchown(2)](https://man7.org/linux/man-pages/man2/lchown.2.html).
    lchown = 4016,
    /// See doc at [break(2)](https://man7.org/linux/man-pages/man2/break.2.html).
    r#break = 4017,
    /// See doc at [unused18(2)](https://man7.org/linux/man-pages/man2/unused18.2.html).
    unused18 = 4018,
    /// See doc at [lseek(2)](https://man7.org/linux/man-pages/man2/lseek.2.html).
    lseek = 4019,
    /// See doc at [getpid(2)](https://man7.org/linux/man-pages/man2/getpid.2.html).
    getpid = 4020,
    /// See doc at [mount(2)](https://man7.org/linux/man-pages/man2/mount.2.html).
    mount = 4021,
    /// See doc at [umount(2)](https://man7.org/linux/man-pages/man2/umount.2.html).
    umount = 4022,
    /// See doc at [setuid(2)](https://man7.org/linux/man-pages/man2/setuid.2.html).
    setuid = 4023,
    /// See doc at [getuid(2)](https://man7.org/linux/man-pages/man2/getuid.2.html).
    getuid = 4024,
    /// See doc at [stime(2)](https://man7.org/linux/man-pages/man2/stime.2.html).
    stime = 4025,
    /// See doc at [ptrace(2)](https://man7.org/linux/man-pages/man2/ptrace.2.html).
    ptrace = 4026,
    /// See doc at [alarm(2)](https://man7.org/linux/man-pages/man2/alarm.2.html).
    alarm = 4027,
    /// See doc at [unused28(2)](https://man7.org/linux/man-pages/man2/unused28.2.html).
    unused28 = 4028,
    /// See doc at [pause(2)](https://man7.org/linux/man-pages/man2/pause.2.html).
    pause = 4029,
    /// See doc at [utime(2)](https://man7.org/linux/man-pages/man2/utime.2.html).
    utime = 4030,
    /// See doc at [stty(2)](https://man7.org/linux/man-pages/man2/stty.2.html).
    stty = 4031,
    /// See doc at [gtty(2)](https://man7.org/linux/man-pages/man2/gtty.2.html).
    gtty = 4032,
    /// See doc at [access(2)](https://man7.org/linux/man-pages/man2/access.2.html).
    access = 4033,
    /// See doc at [nice(2)](https://man7.org/linux/man-pages/man2/nice.2.html).
    nice = 4034,
    /// See doc at [ftime(2)](https://man7.org/linux/man-pages/man2/ftime.2.html).
    ftime = 4035,
    /// See doc at [sync(2)](https://man7.org/linux/man-pages/man2/sync.2.html).
    sync = 4036,
    /// See doc at [kill(2)](https://man7.org/linux/man-pages/man2/kill.2.html).
    kill = 4037,
    /// See doc at [rename(2)](https://man7.org/linux/man-pages/man2/rename.2.html).
    rename = 4038,
    /// See doc at [mkdir(2)](https://man7.org/linux/man-pages/man2/mkdir.2.html).
    mkdir = 4039,
    /// See doc at [rmdir(2)](https://man7.org/linux/man-pages/man2/rmdir.2.html).
    rmdir = 4040,
    /// See doc at [dup(2)](https://man7.org/linux/man-pages/man2/dup.2.html).
    dup = 4041,
    /// See doc at [pipe(2)](https://man7.org/linux/man-pages/man2/pipe.2.html).
    pipe = 4042,
    /// See doc at [times(2)](https://man7.org/linux/man-pages/man2/times.2.html).
    times = 4043,
    /// See doc at [prof(2)](https://man7.org/linux/man-pages/man2/prof.2.html).
    prof = 4044,
    /// See doc at [brk(2)](https://man7.org/linux/man-pages/man2/brk.2.html).
    brk = 4045,
    /// See doc at [setgid(2)](https://man7.org/linux/man-pages/man2/setgid.2.html).
    setgid = 4046,
    /// See doc at [getgid(2)](https://man7.org/linux/man-pages/man2/getgid.2.html).
    getgid = 4047,
    /// See doc at [signal(2)](https://man7.org/linux/man-pages/man2/signal.2.html).
    signal = 4048,
    /// See doc at [geteuid(2)](https://man7.org/linux/man-pages/man2/geteuid.2.html).
    geteuid = 4049,
    /// See doc at [getegid(2)](https://man7.org/linux/man-pages/man2/getegid.2.html).
    getegid = 4050,
    /// See doc at [acct(2)](https://man7.org/linux/man-pages/man2/acct.2.html).
    acct = 4051,
    /// See doc at [umount2(2)](https://man7.org/linux/man-pages/man2/umount2.2.html).
    umount2 = 4052,
    /// See doc at [lock(2)](https://man7.org/linux/man-pages/man2/lock.2.html).
    lock = 4053,
    /// See doc at [ioctl(2)](https://man7.org/linux/man-pages/man2/ioctl.2.html).
    ioctl = 4054,
    /// See doc at [fcntl(2)](https://man7.org/linux/man-pages/man2/fcntl.2.html).
    fcntl = 4055,
    /// See doc at [mpx(2)](https://man7.org/linux/man-pages/man2/mpx.2.html).
    mpx = 4056,
    /// See doc at [setpgid(2)](https://man7.org/linux/man-pages/man2/setpgid.2.html).
    setpgid = 4057,
    /// See doc at [ulimit(2)](https://man7.org/linux/man-pages/man2/ulimit.2.html).
    ulimit = 4058,
    /// See doc at [unused59(2)](https://man7.org/linux/man-pages/man2/unused59.2.html).
    unused59 = 4059,
    /// See doc at [umask(2)](https://man7.org/linux/man-pages/man2/umask.2.html).
    umask = 4060,
    /// See doc at [chroot(2)](https://man7.org/linux/man-pages/man2/chroot.2.html).
    chroot = 4061,
    /// See doc at [ustat(2)](https://man7.org/linux/man-pages/man2/ustat.2.html).
    ustat = 4062,
    /// See doc at [dup2(2)](https://man7.org/linux/man-pages/man2/dup2.2.html).
    dup2 = 4063,
    /// See doc at [getppid(2)](https://man7.org/linux/man-pages/man2/getppid.2.html).
    getppid = 4064,
    /// See doc at [getpgrp(2)](https://man7.org/linux/man-pages/man2/getpgrp.2.html).
    getpgrp = 4065,
    /// See doc at [setsid(2)](https://man7.org/linux/man-pages/man2/setsid.2.html).
    setsid = 4066,
    /// See doc at [sigaction(2)](https://man7.org/linux/man-pages/man2/sigaction.2.html).
    sigaction = 4067,
    /// See doc at [sgetmask(2)](https://man7.org/linux/man-pages/man2/sgetmask.2.html).
    sgetmask = 4068,
    /// See doc at [ssetmask(2)](https://man7.org/linux/man-pages/man2/ssetmask.2.html).
    ssetmask = 4069,
    /// See doc at [setreuid(2)](https://man7.org/linux/man-pages/man2/setreuid.2.html).
    setreuid = 4070,
    /// See doc at [setregid(2)](https://man7.org/linux/man-pages/man2/setregid.2.html).
    setregid = 4071,
    /// See doc at [sigsuspend(2)](https://man7.org/linux/man-pages/man2/sigsuspend.2.html).
    sigsuspend = 4072,
    /// See doc at [sigpending(2)](https://man7.org/linux/man-pages/man2/sigpending.2.html).
    sigpending = 4073,
    /// See doc at [sethostname(2)](https://man7.org/linux/man-pages/man2/sethostname.2.html).
    sethostname = 4074,
    /// See doc at [setrlimit(2)](https://man7.org/linux/man-pages/man2/setrlimit.2.html).
    setrlimit = 4075,
    /// See doc at [getrlimit(2)](https://man7.org/linux/man-pages/man2/getrlimit.2.html).
    getrlimit = 4076,
    /// See doc at [getrusage(2)](https://man7.org/linux/man-pages/man2/getrusage.2.html).
    getrusage = 4077,
    /// See doc at [gettimeofday(2)](https://man7.org/linux/man-pages/man2/gettimeofday.2.html).
    gettimeofday = 4078,
    /// See doc at [settimeofday(2)](https://man7.org/linux/man-pages/man2/settimeofday.2.html).
    settimeofday = 4079,
    /// See doc at [getgroups(2)](https://man7.org/linux/man-pages/man2/getgroups.2.html).
    getgroups = 4080,
    /// See doc at [setgroups(2)](https://man7.org/linux/man-pages/man2/setgroups.2.html).
    setgroups = 4081,
    /// See doc at [reserved82(2)](https://man7.org/linux/man-pages/man2/reserved82.2.html).
    reserved82 = 4082,
    /// See doc at [symlink(2)](https://man7.org/linux/man-pages/man2/symlink.2.html).
    symlink = 4083,
    /// See doc at [unused84(2)](https://man7.org/linux/man-pages/man2/unused84.2.html).
    unused84 = 4084,
    /// See doc at [readlink(2)](https://man7.org/linux/man-pages/man2/readlink.2.html).
    readlink = 4085,
    /// See doc at [uselib(2)](https://man7.org/linux/man-pages/man2/uselib.2.html).
    uselib = 4086,
    /// See doc at [swapon(2)](https://man7.org/linux/man-pages/man2/swapon.2.html).
    swapon = 4087,
    /// See doc at [reboot(2)](https://man7.org/linux/man-pages/man2/reboot.2.html).
    reboot = 4088,
    /// See doc at [readdir(2)](https://man7.org/linux/man-pages/man2/readdir.2.html).
    readdir = 4089,
    /// See doc at [mmap(2)](https://man7.org/linux/man-pages/man2/mmap.2.html).
    mmap = 4090,
    /// See doc at [munmap(2)](https://man7.org/linux/man-pages/man2/munmap.2.html).
    munmap = 4091,
    /// See doc at [truncate(2)](https://man7.org/linux/man-pages/man2/truncate.2.html).
    truncate = 4092,
    /// See doc at [ftruncate(2)](https://man7.org/linux/man-pages/man2/ftruncate.2.html).
    ftruncate = 4093,
    /// See doc at [fchmod(2)](https://man7.org/linux/man-pages/man2/fchmod.2.html).
    fchmod = 4094,
    /// See doc at [fchown(2)](https://man7.org/linux/man-pages/man2/fchown.2.html).
    fchown = 4095,
    /// See doc at [getpriority(2)](https://man7.org/linux/man-pages/man2/getpriority.2.html).
    getpriority = 4096,
    /// See doc at [setpriority(2)](https://man7.org/linux/man-pages/man2/setpriority.2.html).
    setpriority = 4097,
    /// See doc at [profil(2)](https://man7.org/linux/man-pages/man2/profil.2.html).
    profil = 4098,
    /// See doc at [statfs(2)](https://man7.org/linux/man-pages/man2/statfs.2.html).
    statfs = 4099,
    /// See doc at [fstatfs(2)](https://man7.org/linux/man-pages/man2/fstatfs.2.html).
    fstatfs = 4100,
    /// See doc at [ioperm(2)](https://man7.org/linux/man-pages/man2/ioperm.2.html).
    ioperm = 4101,
    /// See doc at [socketcall(2)](https://man7.org/linux/man-pages/man2/socketcall.2.html).
    socketcall = 4102,
    /// See doc at [syslog(2)](https://man7.org/linux/man-pages/man2/syslog.2.html).
    syslog = 4103,
    /// See doc at [setitimer(2)](https://man7.org/linux/man-pages/man2/setitimer.2.html).
    setitimer = 4104,
    /// See doc at [getitimer(2)](https://man7.org/linux/man-pages/man2/getitimer.2.html).
    getitimer = 4105,
    /// See doc at [stat(2)](https://man7.org/linux/man-pages/man2/stat.2.html).
    stat = 4106,
    /// See doc at [lstat(2)](https://man7.org/linux/man-pages/man2/lstat.2.html).
    lstat = 4107,
    /// See doc at [fstat(2)](https://man7.org/linux/man-pages/man2/fstat.2.html).
    fstat = 4108,
    /// See doc at [unused109(2)](https://man7.org/linux/man-pages/man2/unused109.2.html).
    unused109 = 4109,
    /// See doc at [iopl(2)](https://man7.org/linux/man-pages/man2/iopl.2.html).
    iopl = 4110,
    /// See doc at [vhangup(2)](https://man7.org/linux/man-pages/man2/vhangup.2.html).
    vhangup = 4111,
    /// See doc at [idle(2)](https://man7.org/linux/man-pages/man2/idle.2.html).
    idle = 4112,
    /// See doc at [vm86(2)](https://man7.org/linux/man-pages/man2/vm86.2.html).
    vm86 = 4113,
    /// See doc at [wait4(2)](https://man7.org/linux/man-pages/man2/wait4.2.html).
    wait4 = 4114,
    /// See doc at [swapoff(2)](https://man7.org/linux/man-pages/man2/swapoff.2.html).
    swapoff = 4115,
    /// See doc at [sysinfo(2)](https://man7.org/linux/man-pages/man2/sysinfo.2.html).
    sysinfo = 4116,
    /// See doc at [ipc(2)](https://man7.org/linux/man-pages/man2/ipc.2.html).
    ipc = 4117,
    /// See doc at [fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html).
    fsync = 4118,
    /// See doc at [sigreturn(2)](https://man7.org/linux/man-pages/man2/sigreturn.2.html).
    sigreturn = 4119,
    /// See doc at [clone(2)](https://man7.org/linux/man-pages/man2/clone.2.html).
    clone = 4120,
    /// See doc at [setdomainname(2)](https://man7.org/linux/man-pages/man2/setdomainname.2.html).
    setdomainname = 4121,
    /// See doc at [uname(2)](https://man7.org/linux/man-pages/man2/uname.2.html).
    uname = 4122,
    /// See doc at [modify_ldt(2)](https://man7.org/linux/man-pages/man2/modify_ldt.2.html).
    modify_ldt = 4123,
    /// See doc at [adjtimex(2)](https://man7.org/linux/man-pages/man2/adjtimex.2.html).
    adjtimex = 4124,
    /// See doc at [mprotect(2)](https://man7.org/linux/man-pages/man2/mprotect.2.html).
    mprotect = 4125,
    /// See doc at [sigprocmask(2)](https://man7.org/linux/man-pages/man2/sigprocmask.2.html).
    sigprocmask = 4126,
    /// See doc at [create_module(2)](https://man7.org/linux/man-pages/man2/create_module.2.html).
    create_module = 4127,
    /// See doc at [init_module(2)](https://man7.org/linux/man-pages/man2/init_module.2.html).
    init_module = 4128,
    /// See doc at [delete_module(2)](https://man7.org/linux/man-pages/man2/delete_module.2.html).
    delete_module = 4129,
    /// See doc at [get_kernel_syms(2)](https://man7.org/linux/man-pages/man2/get_kernel_syms.2.html).
    get_kernel_syms = 4130,
    /// See doc at [quotactl(2)](https://man7.org/linux/man-pages/man2/quotactl.2.html).
    quotactl = 4131,
    /// See doc at [getpgid(2)](https://man7.org/linux/man-pages/man2/getpgid.2.html).
    getpgid = 4132,
    /// See doc at [fchdir(2)](https://man7.org/linux/man-pages/man2/fchdir.2.html).
    fchdir = 4133,
    /// See doc at [bdflush(2)](https://man7.org/linux/man-pages/man2/bdflush.2.html).
    bdflush = 4134,
    /// See doc at [sysfs(2)](https://man7.org/linux/man-pages/man2/sysfs.2.html).
    sysfs = 4135,
    /// See doc at [personality(2)](https://man7.org/linux/man-pages/man2/personality.2.html).
    personality = 4136,
    /// See doc at [afs_syscall(2)](https://man7.org/linux/man-pages/man2/afs_syscall.2.html).
    afs_syscall = 4137,
    /// See doc at [setfsuid(2)](https://man7.org/linux/man-pages/man2/setfsuid.2.html).
    setfsuid = 4138,
    /// See doc at [setfsgid(2)](https://man7.org/linux/man-pages/man2/setfsgid.2.html).
    setfsgid = 4139,
    /// See doc at [_llseek(2)](https://man7.org/linux/man-pages/man2/_llseek.2.html).
    _llseek = 4140,
    /// See doc at [getdents(2)](https://man7.org/linux/man-pages/man2/getdents.2.html).
    getdents = 4141,
    /// See doc at [_newselect(2)](https://man7.org/linux/man-pages/man2/_newselect.2.html).
    _newselect = 4142,
    /// See doc at [flock(2)](https://man7.org/linux/man-pages/man2/flock.2.html).
    flock = 4143,
    /// See doc at [msync(2)](https://man7.org/linux/man-pages/man2/msync.2.html).
    msync = 4144,
    /// See doc at [readv(2)](https://man7.org/linux/man-pages/man2/readv.2.html).
    readv = 4145,
    /// See doc at [writev(2)](https://man7.org/linux/man-pages/man2/writev.2.html).
    writev = 4146,
    /// See doc at [cacheflush(2)](https://man7.org/linux/man-pages/man2/cacheflush.2.html).
    cacheflush = 4147,
    /// See doc at [cachectl(2)](https://man7.org/linux/man-pages/man2/cachectl.2.html).
    cachectl = 4148,
    /// See doc at [sysmips(2)](https://man7.org/linux/man-pages/man2/sysmips.2.html).
    sysmips = 4149,
    /// See doc at [unused150(2)](https://man7.org/linux/man-pages/man2/unused150.2.html).
    unused150 = 4150,
    /// See doc at [getsid(2)](https://man7.org/linux/man-pages/man2/getsid.2.html).
    getsid = 4151,
    /// See doc at [fdatasync(2)](https://man7.org/linux/man-pages/man2/fdatasync.2.html).
    fdatasync = 4152,
    /// See doc at [_sysctl(2)](https://man7.org/linux/man-pages/man2/_sysctl.2.html).
    _sysctl = 4153,
    /// See doc at [mlock(2)](https://man7.org/linux/man-pages/man2/mlock.2.html).
    mlock = 4154,
    /// See doc at [munlock(2)](https://man7.org/linux/man-pages/man2/munlock.2.html).
    munlock = 4155,
    /// See doc at [mlockall(2)](https://man7.org/linux/man-pages/man2/mlockall.2.html).
    mlockall = 4156,
    /// See doc at [munlockall(2)](https://man7.org/linux/man-pages/man2/munlockall.2.html).
    munlockall = 4157,
    /// See doc at [sched_setparam(2)](https://man7.org/linux/man-pages/man2/sched_setparam.2.html).
    sched_setparam = 4158,
    /// See doc at [sched_getparam(2)](https://man7.org/linux/man-pages/man2/sched_getparam.2.html).
    sched_getparam = 4159,
    /// See doc at [sched_setscheduler(2)](https://man7.org/linux/man-pages/man2/sched_setscheduler.2.html).
    sched_setscheduler = 4160,
    /// See doc at [sched_getscheduler(2)](https://man7.org/linux/man-pages/man2/sched_getscheduler.2.html).
    sched_getscheduler = 4161,
    /// See doc at [sched_yield(2)](https://man7.org/linux/man-pages/man2/sched_yield.2.html).
    sched_yield = 4162,
    /// See doc at [sched_get_priority_max(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_max.2.html).
    sched_get_priority_max = 4163,
    /// See doc at [sched_get_priority_min(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_min.2.html).
    sched_get_priority_min = 4164,
    /// See doc at [sched_rr_get_interval(2)](https://man7.org/linux/man-pages/man2/sched_rr_get_interval.2.html).
    sched_rr_get_interval = 4165,
    /// See doc at [nanosleep(2)](https://man7.org/linux/man-pages/man2/nanosleep.2.html).
    nanosleep = 4166,
    /// See doc at [mremap(2)](https://man7.org/linux/man-pages/man2/mremap.2.html).
    mremap = 4167,
    /// See doc at [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html).
    accept = 4168,
    /// See doc at [bind(2)](https://man7.org/linux/man-pages/man2/bind.2.html).
    bind = 4169,
    /// See doc at [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html).
    connect = 4170,
    /// See doc at [getpeername(2)](https://man7.org/linux/man-pages/man2/getpeername.2.html).
    getpeername = 4171,
    /// See doc at [getsockname(2)](https://man7.org/linux/man-pages/man2/getsockname.2.html).
    getsockname = 4172,
    /// See doc at [getsockopt(2)](https://man7.org/linux/man-pages/man2/getsockopt.2.html).
    getsockopt = 4173,
    /// See doc at [listen(2)](https://man7.org/linux/man-pages/man2/listen.2.html).
    listen = 4174,
    /// See doc at [recv(2)](https://man7.org/linux/man-pages/man2/recv.2.html).
    recv = 4175,
    /// See doc at [recvfrom(2)](https://man7.org/linux/man-pages/man2/recvfrom.2.html).
    recvfrom = 4176,
    /// See doc at [recvmsg(2)](https://man7.org/linux/man-pages/man2/recvmsg.2.html).
    recvmsg = 4177,
    /// See doc at [send(2)](https://man7.org/linux/man-pages/man2/send.2.html).
    send = 4178,
    /// See doc at [sendmsg(2)](https://man7.org/linux/man-pages/man2/sendmsg.2.html).
    sendmsg = 4179,
    /// See doc at [sendto(2)](https://man7.org/linux/man-pages/man2/sendto.2.html).
    sendto = 4180,
    /// See doc at [setsockopt(2)](https://man7.org/linux/man-pages/man2/setsockopt.2.html).
    setsockopt = 4181,
    /// See doc at [shutdown(2)](https://man7.org/linux/man-pages/man2/shutdown.2.html).
    shutdown = 4182,
    /// See doc at [socket(2)](https://man7.org/linux/man-pages/man2/socket.2.html).
    socket = 4183,
    /// See doc at [socketpair(2)](https://man7.org/linux/man-pages/man2/socketpair.2.html).
    socketpair = 4184,
    /// See doc at [setresuid(2)](https://man7.org/linux/man-pages/man2/setresuid.2.html).
    setresuid = 4185,
    /// See doc at [getresuid(2)](https://man7.org/linux/man-pages/man2/getresuid.2.html).
    getresuid = 4186,
    /// See doc at [query_module(2)](https://man7.org/linux/man-pages/man2/query_module.2.html).
    query_module = 4187,
    /// See doc at [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html).
    poll = 4188,
    /// See doc at [nfsservctl(2)](https://man7.org/linux/man-pages/man2/nfsservctl.2.html).
    nfsservctl = 4189,
    /// See doc at [setresgid(2)](https://man7.org/linux/man-pages/man2/setresgid.2.html).
    setresgid = 4190,
    /// See doc at [getresgid(2)](https://man7.org/linux/man-pages/man2/getresgid.2.html).
    getresgid = 4191,
    /// See doc at [prctl(2)](https://man7.org/linux/man-pages/man2/prctl.2.html).
    prctl = 4192,
    /// See doc at [rt_sigreturn(2)](https://man7.org/linux/man-pages/man2/rt_sigreturn.2.html).
    rt_sigreturn = 4193,
    /// See doc at [rt_sigaction(2)](https://man7.org/linux/man-pages/man2/rt_sigaction.2.html).
    rt_sigaction = 4194,
    /// See doc at [rt_sigprocmask(2)](https://man7.org/linux/man-pages/man2/rt_sigprocmask.2.html).
    rt_sigprocmask = 4195,
    /// See doc at [rt_sigpending(2)](https://man7.org/linux/man-pages/man2/rt_sigpending.2.html).
    rt_sigpending = 4196,
    /// See doc at [rt_sigtimedwait(2)](https://man7.org/linux/man-pages/man2/rt_sigtimedwait.2.html).
    rt_sigtimedwait = 4197,
    /// See doc at [rt_sigqueueinfo(2)](https://man7.org/linux/man-pages/man2/rt_sigqueueinfo.2.html).
    rt_sigqueueinfo = 4198,
    /// See doc at [rt_sigsuspend(2)](https://man7.org/linux/man-pages/man2/rt_sigsuspend.2.html).
    rt_sigsuspend = 4199,
    /// See doc at [pread64(2)](https://man7.org/linux/man-pages/man2/pread64.2.html).
    pread64 = 4200,
    /// See doc at [pwrite64(2)](https://man7.org/linux/man-pages/man2/pwrite64.2.html).
    pwrite64 = 4201,
    /// See doc at [chown(2)](https://man7.org/linux/man-pages/man2/chown.2.html).
    chown = 4202,
    /// See doc at [getcwd(2)](https://man7.org/linux/man-pages/man2/getcwd.2.html).
    getcwd = 4203,
    /// See doc at [capget(2)](https://man7.org/linux/man-pages/man2/capget.2.html).
    capget = 4204,
    /// See doc at [capset(2)](https://man7.org/linux/man-pages/man2/capset.2.html).
    capset = 4205,
    /// See doc at [sigaltstack(2)](https://man7.org/linux/man-pages/man2/sigaltstack.2.html).
    sigaltstack = 4206,
    /// See doc at [sendfile(2)](https://man7.org/linux/man-pages/man2/sendfile.2.html).
    sendfile = 4207,
    /// See doc at [getpmsg(2)](https://man7.org/linux/man-pages/man2/getpmsg.2.html).
    getpmsg = 4208,
    /// See doc at [putpmsg(2)](https://man7.org/linux/man-pages/man2/putpmsg.2.html).
    putpmsg = 4209,
    /// See doc at [mmap2(2)](https://man7.org/linux/man-pages/man2/mmap2.2.html).
    mmap2 = 4210,
    /// See doc at [truncate64(2)](https://man7.org/linux/man-pages/man2/truncate64.2.html).
    truncate64 = 4211,
    /// See doc at [ftruncate64(2)](https://man7.org/linux/man-pages/man2/ftruncate64.2.html).
    ftruncate64 = 4212,
    /// See doc at [stat64(2)](https://man7.org/linux/man-pages/man2/stat64.2.html).
    stat64 = 4213,
    /// See doc at [lstat64(2)](https://man7.org/linux/man-pages/man2/lstat64.2.html).
    lstat64 = 4214,
    /// See doc at [fstat64(2)](https://man7.org/linux/man-pages/man2/fstat64.2.html).
    fstat64 = 4215,
    /// See doc at [pivot_root(2)](https://man7.org/linux/man-pages/man2/pivot_root.2.html).
    pivot_root = 4216,
    /// See doc at [mincore(2)](https://man7.org/linux/man-pages/man2/mincore.2.html).
    mincore = 4217,
    /// See doc at [madvise(2)](https://man7.org/linux/man-pages/man2/madvise.2.html).
    madvise = 4218,
    /// See doc at [getdents64(2)](https://man7.org/linux/man-pages/man2/getdents64.2.html).
    getdents64 = 4219,
    /// See doc at [fcntl64(2)](https://man7.org/linux/man-pages/man2/fcntl64.2.html).
    fcntl64 = 4220,
    /// See doc at [reserved221(2)](https://man7.org/linux/man-pages/man2/reserved221.2.html).
    reserved221 = 4221,
    /// See doc at [gettid(2)](https://man7.org/linux/man-pages/man2/gettid.2.html).
    gettid = 4222,
    /// See doc at [readahead(2)](https://man7.org/linux/man-pages/man2/readahead.2.html).
    readahead = 4223,
    /// See doc at [setxattr(2)](https://man7.org/linux/man-pages/man2/setxattr.2.html).
    setxattr = 4224,
    /// See doc at [lsetxattr(2)](https://man7.org/linux/man-pages/man2/lsetxattr.2.html).
    lsetxattr = 4225,
    /// See doc at [fsetxattr(2)](https://man7.org/linux/man-pages/man2/fsetxattr.2.html).
    fsetxattr = 4226,
    /// See doc at [getxattr(2)](https://man7.org/linux/man-pages/man2/getxattr.2.html).
    getxattr = 4227,
    /// See doc at [lgetxattr(2)](https://man7.org/linux/man-pages/man2/lgetxattr.2.html).
    lgetxattr = 4228,
    /// See doc at [fgetxattr(2)](https://man7.org/linux/man-pages/man2/fgetxattr.2.html).
    fgetxattr = 4229,
    /// See doc at [listxattr(2)](https://man7.org/linux/man-pages/man2/listxattr.2.html).
    listxattr = 4230,
    /// See doc at [llistxattr(2)](https://man7.org/linux/man-pages/man2/llistxattr.2.html).
    llistxattr = 4231,
    /// See doc at [flistxattr(2)](https://man7.org/linux/man-pages/man2/flistxattr.2.html).
    flistxattr = 4232,
    /// See doc at [removexattr(2)](https://man7.org/linux/man-pages/man2/removexattr.2.html).
    removexattr = 4233,
    /// See doc at [lremovexattr(2)](https://man7.org/linux/man-pages/man2/lremovexattr.2.html).
    lremovexattr = 4234,
    /// See doc at [fremovexattr(2)](https://man7.org/linux/man-pages/man2/fremovexattr.2.html).
    fremovexattr = 4235,
    /// See doc at [tkill(2)](https://man7.org/linux/man-pages/man2/tkill.2.html).
    tkill = 4236,
    /// See doc at [sendfile64(2)](https://man7.org/linux/man-pages/man2/sendfile64.2.html).
    sendfile64 = 4237,
    /// See doc at [futex(2)](https://man7.org/linux/man-pages/man2/futex.2.html).
    futex = 4238,
    /// See doc at [sched_setaffinity(2)](https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html).
    sched_setaffinity = 4239,
    /// See doc at [sched_getaffinity(2)](https://man7.org/linux/man-pages/man2/sched_getaffinity.2.html).
    sched_getaffinity = 4240,
    /// See doc at [io_setup(2)](https://man7.org/linux/man-pages/man2/io_setup.2.html).
    io_setup = 4241,
    /// See doc at [io_destroy(2)](https://man7.org/linux/man-pages/man2/io_destroy.2.html).
    io_destroy = 4242,
    /// See doc at [io_getevents(2)](https://man7.org/linux/man-pages/man2/io_getevents.2.html).
    io_getevents = 4243,
    /// See doc at [io_submit(2)](https://man7.org/linux/man-pages/man2/io_submit.2.html).
    io_submit = 4244,
    /// See doc at [io_cancel(2)](https://man7.org/linux/man-pages/man2/io_cancel.2.html).
    io_cancel = 4245,
    /// See doc at [exit_group(2)](https://man7.org/linux/man-pages/man2/exit_group.2.html).
    exit_group = 4246,
    /// See doc at [lookup_dcookie(2)](https://man7.org/linux/man-pages/man2/lookup_dcookie.2.html).
    lookup_dcookie = 4247,
    /// See doc at [epoll_create(2)](https://man7.org/linux/man-pages/man2/epoll_create.2.html).
    epoll_create = 4248,
    /// See doc at [epoll_ctl(2)](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html).
    epoll_ctl = 4249,
    /// See doc at [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html).
    epoll_wait = 4250,
    /// See doc at [remap_file_pages(2)](https://man7.org/linux/man-pages/man2/remap_file_pages.2.html).
    remap_file_pages = 4251,
    /// See doc at [set_tid_address(2)](https://man7.org/linux/man-pages/man2/set_tid_address.2.html).
    set_tid_address = 4252,
    /// See doc at [restart_syscall(2)](https://man7.org/linux/man-pages/man2/restart_syscall.2.html).
    restart_syscall = 4253,
    /// See doc at [fadvise64(2)](https://man7.org/linux/man-pages/man2/fadvise64.2.html).
    fadvise64 = 4254,
    /// See doc at [statfs64(2)](https://man7.org/linux/man-pages/man2/statfs64.2.html).
    statfs64 = 4255,
    /// See doc at [fstatfs64(2)](https://man7.org/linux/man-pages/man2/fstatfs64.2.html).
    fstatfs64 = 4256,
    /// See doc at [timer_create(2)](https://man7.org/linux/man-pages/man2/timer_create.2.html).
    timer_create = 4257,
    /// See doc at [timer_settime(2)](https://man7.org/linux/man-pages/man2/timer_settime.2.html).
    timer_settime = 4258,
    /// See doc at [timer_gettime(2)](https://man7.org/linux/man-pages/man2/timer_gettime.2.html).
    timer_gettime = 4259,
    /// See doc at [timer_getoverrun(2)](https://man7.org/linux/man-pages/man2/timer_getoverrun.2.html).
    timer_getoverrun = 4260,
    /// See doc at [timer_delete(2)](https://man7.org/linux/man-pages/man2/timer_delete.2.html).
    timer_delete = 4261,
    /// See doc at [clock_settime(2)](https://man7.org/linux/man-pages/man2/clock_settime.2.html).
    clock_settime = 4262,
    /// See doc at [clock_gettime(2)](https://man7.org/linux/man-pages/man2/clock_gettime.2.html).
    clock_gettime = 4263,
    /// See doc at [clock_getres(2)](https://man7.org/linux/man-pages/man2/clock_getres.2.html).
    clock_getres = 4264,
    /// See doc at [clock_nanosleep(2)](https://man7.org/linux/man-pages/man2/clock_nanosleep.2.html).
    clock_nanosleep = 4265,
    /// See doc at [tgkill(2)](https://man7.org/linux/man-pages/man2/tgkill.2.html).
    tgkill = 4266,
    /// See doc at [utimes(2)](https://man7.org/linux/man-pages/man2/utimes.2.html).
    utimes = 4267,
    /// See doc at [mbind(2)](https://man7.org/linux/man-pages/man2/mbind.2.html).
    mbind = 4268,
    /// See doc at [get_mempolicy(2)](https://man7.org/linux/man-pages/man2/get_mempolicy.2.html).
    get_mempolicy = 4269,
    /// See doc at [set_mempolicy(2)](https://man7.org/linux/man-pages/man2/set_mempolicy.2.html).
    set_mempolicy = 4270,
    /// See doc at [mq_open(2)](https://man7.org/linux/man-pages/man2/mq_open.2.html).
    mq_open = 4271,
    /// See doc at [mq_unlink(2)](https://man7.org/linux/man-pages/man2/mq_unlink.2.html).
    mq_unlink = 4272,
    /// See doc at [mq_timedsend(2)](https://man7.org/linux/man-pages/man2/mq_timedsend.2.html).
    mq_timedsend = 4273,
    /// See doc at [mq_timedreceive(2)](https://man7.org/linux/man-pages/man2/mq_timedreceive.2.html).
    mq_timedreceive = 4274,
    /// See doc at [mq_notify(2)](https://man7.org/linux/man-pages/man2/mq_notify.2.html).
    mq_notify = 4275,
    /// See doc at [mq_getsetattr(2)](https://man7.org/linux/man-pages/man2/mq_getsetattr.2.html).
    mq_getsetattr = 4276,
    /// See doc at [vserver(2)](https://man7.org/linux/man-pages/man2/vserver.2.html).
    vserver = 4277,
    /// See doc at [waitid(2)](https://man7.org/linux/man-pages/man2/waitid.2.html).
    waitid = 4278,
    /// See doc at [add_key(2)](https://man7.org/linux/man-pages/man2/add_key.2.html).
    add_key = 4280,
    /// See doc at [request_key(2)](https://man7.org/linux/man-pages/man2/request_key.2.html).
    request_key = 4281,
    /// See doc at [keyctl(2)](https://man7.org/linux/man-pages/man2/keyctl.2.html).
    keyctl = 4282,
    /// See doc at [set_thread_area(2)](https://man7.org/linux/man-pages/man2/set_thread_area.2.html).
    set_thread_area = 4283,
    /// See doc at [inotify_init(2)](https://man7.org/linux/man-pages/man2/inotify_init.2.html).
    inotify_init = 4284,
    /// See doc at [inotify_add_watch(2)](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html).
    inotify_add_watch = 4285,
    /// See doc at [inotify_rm_watch(2)](https://man7.org/linux/man-pages/man2/inotify_rm_watch.2.html).
    inotify_rm_watch = 4286,
    /// See doc at [migrate_pages(2)](https://man7.org/linux/man-pages/man2/migrate_pages.2.html).
    migrate_pages = 4287,
    /// See doc at [openat(2)](https://man7.org/linux/man-pages/man2/openat.2.html).
    openat = 4288,
    /// See doc at [mkdirat(2)](https://man7.org/linux/man-pages/man2/mkdirat.2.html).
    mkdirat = 4289,
    /// See doc at [mknodat(2)](https://man7.org/linux/man-pages/man2/mknodat.2.html).
    mknodat = 4290,
    /// See doc at [fchownat(2)](https://man7.org/linux/man-pages/man2/fchownat.2.html).
    fchownat = 4291,
    /// See doc at [futimesat(2)](https://man7.org/linux/man-pages/man2/futimesat.2.html).
    futimesat = 4292,
    /// See doc at [fstatat64(2)](https://man7.org/linux/man-pages/man2/fstatat64.2.html).
    fstatat64 = 4293,
    /// See doc at [unlinkat(2)](https://man7.org/linux/man-pages/man2/unlinkat.2.html).
    unlinkat = 4294,
    /// See doc at [renameat(2)](https://man7.org/linux/man-pages/man2/renameat.2.html).
    renameat = 4295,
    /// See doc at [linkat(2)](https://man7.org/linux/man-pages/man2/linkat.2.html).
    linkat = 4296,
    /// See doc at [symlinkat(2)](https://man7.org/linux/man-pages/man2/symlinkat.2.html).
    symlinkat = 4297,
    /// See doc at [readlinkat(2)](https://man7.org/linux/man-pages/man2/readlinkat.2.html).
    readlinkat = 4298,
    /// See doc at [fchmodat(2)](https://man7.org/linux/man-pages/man2/fchmodat.2.html).
    fchmodat = 4299,
    /// See doc at [faccessat(2)](https://man7.org/linux/man-pages/man2/faccessat.2.html).
    faccessat = 4300,
    /// See doc at [pselect6(2)](https://man7.org/linux/man-pages/man2/pselect6.2.html).
    pselect6 = 4301,
    /// See doc at [ppoll(2)](https://man7.org/linux/man-pages/man2/ppoll.2.html).
    ppoll = 4302,
    /// See doc at [unshare(2)](https://man7.org/linux/man-pages/man2/unshare.2.html).
    unshare = 4303,
    /// See doc at [splice(2)](https://man7.org/linux/man-pages/man2/splice.2.html).
    splice = 4304,
    /// See doc at [sync_file_range(2)](https://man7.org/linux/man-pages/man2/sync_file_range.2.html).
    sync_file_range = 4305,
    /// See doc at [tee(2)](https://man7.org/linux/man-pages/man2/tee.2.html).
    tee = 4306,
    /// See doc at [vmsplice(2)](https://man7.org/linux/man-pages/man2/vmsplice.2.html).
    vmsplice = 4307,
    /// See doc at [move_pages(2)](https://man7.org/linux/man-pages/man2/move_pages.2.html).
    move_pages = 4308,
    /// See doc at [set_robust_list(2)](https://man7.org/linux/man-pages/man2/set_robust_list.2.html).
    set_robust_list = 4309,
    /// See doc at [get_robust_list(2)](https://man7.org/linux/man-pages/man2/get_robust_list.2.html).
    get_robust_list = 4310,
    /// See doc at [kexec_load(2)](https://man7.org/linux/man-pages/man2/kexec_load.2.html).
    kexec_load = 4311,
    /// See doc at [getcpu(2)](https://man7.org/linux/man-pages/man2/getcpu.2.html).
    getcpu = 4312,
    /// See doc at [epoll_pwait(2)](https://man7.org/linux/man-pages/man2/epoll_pwait.2.html).
    epoll_pwait = 4313,
    /// See doc at [ioprio_set(2)](https://man7.org/linux/man-pages/man2/ioprio_set.2.html).
    ioprio_set = 4314,
    /// See doc at [ioprio_get(2)](https://man7.org/linux/man-pages/man2/ioprio_get.2.html).
    ioprio_get = 4315,
    /// See doc at [utimensat(2)](https://man7.org/linux/man-pages/man2/utimensat.2.html).
    utimensat = 4316,
    /// See doc at [signalfd(2)](https://man7.org/linux/man-pages/man2/signalfd.2.html).
    signalfd = 4317,
    /// See doc at [timerfd(2)](https://man7.org/linux/man-pages/man2/timerfd.2.html).
    timerfd = 4318,
    /// See doc at [eventfd(2)](https://man7.org/linux/man-pages/man2/eventfd.2.html).
    eventfd = 4319,
    /// See doc at [fallocate(2)](https://man7.org/linux/man-pages/man2/fallocate.2.html).
    fallocate = 4320,
    /// See doc at [timerfd_create(2)](https://man7.org/linux/man-pages/man2/timerfd_create.2.html).
    timerfd_create = 4321,
    /// See doc at [timerfd_gettime(2)](https://man7.org/linux/man-pages/man2/timerfd_gettime.2.html).
    timerfd_gettime = 4322,
    /// See doc at [timerfd_settime(2)](https://man7.org/linux/man-pages/man2/timerfd_settime.2.html).
    timerfd_settime = 4323,
    /// See doc at [signalfd4(2)](https://man7.org/linux/man-pages/man2/signalfd4.2.html).
    signalfd4 = 4324,
    /// See doc at [eventfd2(2)](https://man7.org/linux/man-pages/man2/eventfd2.2.html).
    eventfd2 = 4325,
    /// See doc at [epoll_create1(2)](https://man7.org/linux/man-pages/man2/epoll_create1.2.html).
    epoll_create1 = 4326,
    /// See doc at [dup3(2)](https://man7.org/linux/man-pages/man2/dup3.2.html).
    dup3 = 4327,
    /// See doc at [pipe2(2)](https://man7.org/linux/man-pages/man2/pipe2.2.html).
    pipe2 = 4328,
    /// See doc at [inotify_init1(2)](https://man7.org/linux/man-pages/man2/inotify_init1.2.html).
    inotify_init1 = 4329,
    /// See doc at [preadv(2)](https://man7.org/linux/man-pages/man2/preadv.2.html).
    preadv = 4330,
    /// See doc at [pwritev(2)](https://man7.org/linux/man-pages/man2/pwritev.2.html).
    pwritev = 4331,
    /// See doc at [rt_tgsigqueueinfo(2)](https://man7.org/linux/man-pages/man2/rt_tgsigqueueinfo.2.html).
    rt_tgsigqueueinfo = 4332,
    /// See doc at [perf_event_open(2)](https://man7.org/linux/man-pages/man2/perf_event_open.2.html).
    perf_event_open = 4333,
    /// See doc at [accept4(2)](https://man7.org/linux/man-pages/man2/accept4.2.html).
    accept4 = 4334,
    /// See doc at [recvmmsg(2)](https://man7.org/linux/man-pages/man2/recvmmsg.2.html).
    recvmmsg = 4335,
    /// See doc at [fanotify_init(2)](https://man7.org/linux/man-pages/man2/fanotify_init.2.html).
    fanotify_init = 4336,
    /// See doc at [fanotify_mark(2)](https://man7.org/linux/man-pages/man2/fanotify_mark.2.html).
    fanotify_mark = 4337,
    /// See doc at [prlimit64(2)](https://man7.org/linux/man-pages/man2/prlimit64.2.html).
    prlimit64 = 4338,
    /// See doc at [name_to_handle_at(2)](https://man7.org/linux/man-pages/man2/name_to_handle_at.2.html).
    name_to_handle_at = 4339,
    /// See doc at [open_by_handle_at(2)](https://man7.org/linux/man-pages/man2/open_by_handle_at.2.html).
    open_by_handle_at = 4340,
    /// See doc at [clock_adjtime(2)](https://man7.org/linux/man-pages/man2/clock_adjtime.2.html).
    clock_adjtime = 4341,
    /// See doc at [syncfs(2)](https://man7.org/linux/man-pages/man2/syncfs.2.html).
    syncfs = 4342,
    /// See doc at [sendmmsg(2)](https://man7.org/linux/man-pages/man2/sendmmsg.2.html).
    sendmmsg = 4343,
    /// See doc at [setns(2)](https://man7.org/linux/man-pages/man2/setns.2.html).
    setns = 4344,
    /// See doc at [process_vm_readv(2)](https://man7.org/linux/man-pages/man2/process_vm_readv.2.html).
    process_vm_readv = 4345,
    /// See doc at [process_vm_writev(2)](https://man7.org/linux/man-pages/man2/process_vm_writev.2.html).
    process_vm_writev = 4346,
    /// See doc at [kcmp(2)](https://man7.org/linux/man-pages/man2/kcmp.2.html).
    kcmp = 4347,
    /// See doc at [finit_module(2)](https://man7.org/linux/man-pages/man2/finit_module.2.html).
    finit_module = 4348,
    /// See doc at [sched_setattr(2)](https://man7.org/linux/man-pages/man2/sched_setattr.2.html).
    sched_setattr = 4349,
    /// See doc at [sched_getattr(2)](https://man7.org/linux/man-pages/man2/sched_getattr.2.html).
    sched_getattr = 4350,
    /// See doc at [renameat2(2)](https://man7.org/linux/man-pages/man2/renameat2.2.html).
    renameat2 = 4351,
    /// See doc at [seccomp(2)](https://man7.org/linux/man-pages/man2/seccomp.2.html).
    seccomp = 4352,
    /// See doc at [getrandom(2)](https://man7.org/linux/man-pages/man2/getrandom.2.html).
    getrandom = 4353,
    /// See doc at [memfd_create(2)](https://man7.org/linux/man-pages/man2/memfd_create.2.html).
    memfd_create = 4354,
    /// See doc at [bpf(2)](https://man7.org/linux/man-pages/man2/bpf.2.html).
    bpf = 4355,
    /// See doc at [execveat(2)](https://man7.org/linux/man-pages/man2/execveat.2.html).
    execveat = 4356,
    /// See doc at [userfaultfd(2)](https://man7.org/linux/man-pages/man2/userfaultfd.2.html).
    userfaultfd = 4357,
    /// See doc at [membarrier(2)](https://man7.org/linux/man-pages/man2/membarrier.2.html).
    membarrier = 4358,
    /// See doc at [mlock2(2)](https://man7.org/linux/man-pages/man2/mlock2.2.html).
    mlock2 = 4359,
    /// See doc at [copy_file_range(2)](https://man7.org/linux/man-pages/man2/copy_file_range.2.html).
    copy_file_range = 4360,
    /// See doc at [preadv2(2)](https://man7.org/linux/man-pages/man2/preadv2.2.html).
    preadv2 = 4361,
    /// See doc at [pwritev2(2)](https://man7.org/linux/man-pages/man2/pwritev2.2.html).
    pwritev2 = 4362,
    /// See doc at [pkey_mprotect(2)](https://man7.org/linux/man-pages/man2/pkey_mprotect.2.html).
    pkey_mprotect = 4363,
    /// See doc at [pkey_alloc(2)](https://man7.org/linux/man-pages/man2/pkey_alloc.2.html).
    pkey_alloc = 4364,
    /// See doc at [pkey_free(2)](https://man7.org/linux/man-pages/man2/pkey_free.2.html).
    pkey_free = 4365,
    /// See doc at [statx(2)](https://man7.org/linux/man-pages/man2/statx.2.html).
    statx = 4366,
    /// See doc at [rseq(2)](https://man7.org/linux/man-pages/man2/rseq.2.html).
    rseq = 4367,
    /// See doc at [io_pgetevents(2)](https://man7.org/linux/man-pages/man2/io_pgetevents.2.html).
    io_pgetevents = 4368,
    /// See doc at [semget(2)](https://man7.org/linux/man-pages/man2/semget.2.html).
    semget = 4393,
    /// See doc at [semctl(2)](https://man7.org/linux/man-pages/man2/semctl.2.html).
    semctl = 4394,
    /// See doc at [shmget(2)](https://man7.org/linux/man-pages/man2/shmget.2.html).
    shmget = 4395,
    /// See doc at [shmctl(2)](https://man7.org/linux/man-pages/man2/shmctl.2.html).
    shmctl = 4396,
    /// See doc at [shmat(2)](https://man7.org/linux/man-pages/man2/shmat.2.html).
    shmat = 4397,
    /// See doc at [shmdt(2)](https://man7.org/linux/man-pages/man2/shmdt.2.html).
    shmdt = 4398,
    /// See doc at [msgget(2)](https://man7.org/linux/man-pages/man2/msgget.2.html).
    msgget = 4399,
    /// See doc at [msgsnd(2)](https://man7.org/linux/man-pages/man2/msgsnd.2.html).
    msgsnd = 4400,
    /// See doc at [msgrcv(2)](https://man7.org/linux/man-pages/man2/msgrcv.2.html).
    msgrcv = 4401,
    /// See doc at [msgctl(2)](https://man7.org/linux/man-pages/man2/msgctl.2.html).
    msgctl = 4402,
    /// See doc at [clock_gettime64(2)](https://man7.org/linux/man-pages/man2/clock_gettime64.2.html).
    clock_gettime64 = 4403,
    /// See doc at [clock_settime64(2)](https://man7.org/linux/man-pages/man2/clock_settime64.2.html).
    clock_settime64 = 4404,
    /// See doc at [clock_adjtime64(2)](https://man7.org/linux/man-pages/man2/clock_adjtime64.2.html).
    clock_adjtime64 = 4405,
    /// See doc at [clock_getres_time64(2)](https://man7.org/linux/man-pages/man2/clock_getres_time64.2.html).
    clock_getres_time64 = 4406,
    /// See doc at [clock_nanosleep_time64(2)](https://man7.org/linux/man-pages/man2/clock_nanosleep_time64.2.html).
    clock_nanosleep_time64 = 4407,
    /// See doc at [timer_gettime64(2)](https://man7.org/linux/man-pages/man2/timer_gettime64.2.html).
    timer_gettime64 = 4408,
    /// See doc at [timer_settime64(2)](https://man7.org/linux/man-pages/man2/timer_settime64.2.html).
    timer_settime64 = 4409,
    /// See doc at [timerfd_gettime64(2)](https://man7.org/linux/man-pages/man2/timerfd_gettime64.2.html).
    timerfd_gettime64 = 4410,
    /// See doc at [timerfd_settime64(2)](https://man7.org/linux/man-pages/man2/timerfd_settime64.2.html).
    timerfd_settime64 = 4411,
    /// See doc at [utimensat_time64(2)](https://man7.org/linux/man-pages/man2/utimensat_time64.2.html).
    utimensat_time64 = 4412,
    /// See doc at [pselect6_time64(2)](https://man7.org/linux/man-pages/man2/pselect6_time64.2.html).
    pselect6_time64 = 4413,
    /// See doc at [ppoll_time64(2)](https://man7.org/linux/man-pages/man2/ppoll_time64.2.html).
    ppoll_time64 = 4414,
    /// See doc at [io_pgetevents_time64(2)](https://man7.org/linux/man-pages/man2/io_pgetevents_time64.2.html).
    io_pgetevents_time64 = 4416,
    /// See doc at [recvmmsg_time64(2)](https://man7.org/linux/man-pages/man2/recvmmsg_time64.2.html).
    recvmmsg_time64 = 4417,
    /// See doc at [mq_timedsend_time64(2)](https://man7.org/linux/man-pages/man2/mq_timedsend_time64.2.html).
    mq_timedsend_time64 = 4418,
    /// See doc at [mq_timedreceive_time64(2)](https://man7.org/linux/man-pages/man2/mq_timedreceive_time64.2.html).
    mq_timedreceive_time64 = 4419,
    /// See doc at [semtimedop_time64(2)](https://man7.org/linux/man-pages/man2/semtimedop_time64.2.html).
    semtimedop_time64 = 4420,
    /// See doc at [rt_sigtimedwait_time64(2)](https://man7.org/linux/man-pages/man2/rt_sigtimedwait_time64.2.html).
    rt_sigtimedwait_time64 = 4421,
    /// See doc at [futex_time64(2)](https://man7.org/linux/man-pages/man2/futex_time64.2.html).
    futex_time64 = 4422,
    /// See doc at [sched_rr_get_interval_time64(2)](https://man7.org/linux/man-pages/man2/sched_rr_get_interval_time64.2.html).
    sched_rr_get_interval_time64 = 4423,
    /// See doc at [pidfd_send_signal(2)](https://man7.org/linux/man-pages/man2/pidfd_send_signal.2.html).
    pidfd_send_signal = 4424,
    /// See doc at [io_uring_setup(2)](https://man7.org/linux/man-pages/man2/io_uring_setup.2.html).
    io_uring_setup = 4425,
    /// See doc at [io_uring_enter(2)](https://man7.org/linux/man-pages/man2/io_uring_enter.2.html).
    io_uring_enter = 4426,
    /// See doc at [io_uring_register(2)](https://man7.org/linux/man-pages/man2/io_uring_register.2.html).
    io_uring_register = 4427,
    /// See doc at [open_tree(2)](https://man7.org/linux/man-pages/man2/open_tree.2.html).
    open_tree = 4428,
    /// See doc at [move_mount(2)](https://man7.org/linux/man-pages/man2/move_mount.2.html).
    move_mount = 4429,
    /// See doc at [fsopen(2)](https://man7.org/linux/man-pages/man2/fsopen.2.html).
    fsopen = 4430,
    /// See doc at [fsconfig(2)](https://man7.org/linux/man-pages/man2/fsconfig.2.html).
    fsconfig = 4431,
    /// See doc at [fsmount(2)](https://man7.org/linux/man-pages/man2/fsmount.2.html).
    fsmount = 4432,
    /// See doc at [fspick(2)](https://man7.org/linux/man-pages/man2/fspick.2.html).
    fspick = 4433,
    /// See doc at [pidfd_open(2)](https://man7.org/linux/man-pages/man2/pidfd_open.2.html).
    pidfd_open = 4434,
    /// See doc at [clone3(2)](https://man7.org/linux/man-pages/man2/clone3.2.html).
    clone3 = 4435,
    /// See doc at [close_range(2)](https://man7.org/linux/man-pages/man2/close_range.2.html).
    close_range = 4436,
    /// See doc at [openat2(2)](https://man7.org/linux/man-pages/man2/openat2.2.html).
    openat2 = 4437,
    /// See doc at [pidfd_getfd(2)](https://man7.org/linux/man-pages/man2/pidfd_getfd.2.html).
    pidfd_getfd = 4438,
    /// See doc at [faccessat2(2)](https://man7.org/linux/man-pages/man2/faccessat2.2.html).
    faccessat2 = 4439,
    /// See doc at [process_madvise(2)](https://man7.org/linux/man-pages/man2/process_madvise.2.html).
    process_madvise = 4440,
    /// See doc at [epoll_pwait2(2)](https://man7.org/linux/man-pages/man2/epoll_pwait2.2.html).
    epoll_pwait2 = 4441,
    /// See doc at [mount_setattr(2)](https://man7.org/linux/man-pages/man2/mount_setattr.2.html).
    mount_setattr = 4442,
    /// See doc at [quotactl_fd(2)](https://man7.org/linux/man-pages/man2/quotactl_fd.2.html).
    quotactl_fd = 4443,
    /// See doc at [landlock_create_ruleset(2)](https://man7.org/linux/man-pages/man2/landlock_create_ruleset.2.html).
    landlock_create_ruleset = 4444,
    /// See doc at [landlock_add_rule(2)](https://man7.org/linux/man-pages/man2/landlock_add_rule.2.html).
    landlock_add_rule = 4445,
    /// See doc at [landlock_restrict_self(2)](https://man7.org/linux/man-pages/man2/landlock_restrict_self.2.html).
    landlock_restrict_self = 4446,
    /// See doc at [process_mrelease(2)](https://man7.org/linux/man-pages/man2/process_mrelease.2.html).
    process_mrelease = 4448,
    /// See doc at [futex_waitv(2)](https://man7.org/linux/man-pages/man2/futex_waitv.2.html).
    futex_waitv = 4449,
    /// See doc at [set_mempolicy_home_node(2)](https://man7.org/linux/man-pages/man2/set_mempolicy_home_node.2.html).
    set_mempolicy_home_node = 4450,
    /// See doc at [cachestat(2)](https://man7.org/linux/man-pages/man2/cachestat.2.html).
    cachestat = 4451,
    /// See doc at [fchmodat2(2)](https://man7.org/linux/man-pages/man2/fchmodat2.2.html).
    fchmodat2 = 4452,
    /// See doc at [map_shadow_stack(2)](https://man7.org/linux/man-pages/man2/map_shadow_stack.2.html).
    map_shadow_stack = 4453,
    /// See doc at [futex_wake(2)](https://man7.org/linux/man-pages/man2/futex_wake.2.html).
    futex_wake = 4454,
    /// See doc at [futex_wait(2)](https://man7.org/linux/man-pages/man2/futex_wait.2.html).
    futex_wait = 4455,
    /// See doc at [futex_requeue(2)](https://man7.org/linux/man-pages/man2/futex_requeue.2.html).
    futex_requeue = 4456,
    /// See doc at [statmount(2)](https://man7.org/linux/man-pages/man2/statmount.2.html).
    statmount = 4457,
    /// See doc at [listmount(2)](https://man7.org/linux/man-pages/man2/listmount.2.html).
    listmount = 4458,
    /// See doc at [lsm_get_self_attr(2)](https://man7.org/linux/man-pages/man2/lsm_get_self_attr.2.html).
    lsm_get_self_attr = 4459,
    /// See doc at [lsm_set_self_attr(2)](https://man7.org/linux/man-pages/man2/lsm_set_self_attr.2.html).
    lsm_set_self_attr = 4460,
    /// See doc at [lsm_list_modules(2)](https://man7.org/linux/man-pages/man2/lsm_list_modules.2.html).
    lsm_list_modules = 4461,
}
