//! Syscalls for arch `x32`.

#![allow(non_camel_case_types)]

// This file is automatically generated. Do not edit.

/// List of system call numbers.
#[repr(usize)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Sysno {
    /// See doc at [read(2)](https://man7.org/linux/man-pages/man2/read.2.html).
    read = 1073741824,
    /// See doc at [write(2)](https://man7.org/linux/man-pages/man2/write.2.html).
    write = 1073741825,
    /// See doc at [open(2)](https://man7.org/linux/man-pages/man2/open.2.html).
    open = 1073741826,
    /// See doc at [close(2)](https://man7.org/linux/man-pages/man2/close.2.html).
    close = 1073741827,
    /// See doc at [stat(2)](https://man7.org/linux/man-pages/man2/stat.2.html).
    stat = 1073741828,
    /// See doc at [fstat(2)](https://man7.org/linux/man-pages/man2/fstat.2.html).
    fstat = 1073741829,
    /// See doc at [lstat(2)](https://man7.org/linux/man-pages/man2/lstat.2.html).
    lstat = 1073741830,
    /// See doc at [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html).
    poll = 1073741831,
    /// See doc at [lseek(2)](https://man7.org/linux/man-pages/man2/lseek.2.html).
    lseek = 1073741832,
    /// See doc at [mmap(2)](https://man7.org/linux/man-pages/man2/mmap.2.html).
    mmap = 1073741833,
    /// See doc at [mprotect(2)](https://man7.org/linux/man-pages/man2/mprotect.2.html).
    mprotect = 1073741834,
    /// See doc at [munmap(2)](https://man7.org/linux/man-pages/man2/munmap.2.html).
    munmap = 1073741835,
    /// See doc at [brk(2)](https://man7.org/linux/man-pages/man2/brk.2.html).
    brk = 1073741836,
    /// See doc at [rt_sigprocmask(2)](https://man7.org/linux/man-pages/man2/rt_sigprocmask.2.html).
    rt_sigprocmask = 1073741838,
    /// See doc at [pread64(2)](https://man7.org/linux/man-pages/man2/pread64.2.html).
    pread64 = 1073741841,
    /// See doc at [pwrite64(2)](https://man7.org/linux/man-pages/man2/pwrite64.2.html).
    pwrite64 = 1073741842,
    /// See doc at [access(2)](https://man7.org/linux/man-pages/man2/access.2.html).
    access = 1073741845,
    /// See doc at [pipe(2)](https://man7.org/linux/man-pages/man2/pipe.2.html).
    pipe = 1073741846,
    /// See doc at [select(2)](https://man7.org/linux/man-pages/man2/select.2.html).
    select = 1073741847,
    /// See doc at [sched_yield(2)](https://man7.org/linux/man-pages/man2/sched_yield.2.html).
    sched_yield = 1073741848,
    /// See doc at [mremap(2)](https://man7.org/linux/man-pages/man2/mremap.2.html).
    mremap = 1073741849,
    /// See doc at [msync(2)](https://man7.org/linux/man-pages/man2/msync.2.html).
    msync = 1073741850,
    /// See doc at [mincore(2)](https://man7.org/linux/man-pages/man2/mincore.2.html).
    mincore = 1073741851,
    /// See doc at [madvise(2)](https://man7.org/linux/man-pages/man2/madvise.2.html).
    madvise = 1073741852,
    /// See doc at [shmget(2)](https://man7.org/linux/man-pages/man2/shmget.2.html).
    shmget = 1073741853,
    /// See doc at [shmat(2)](https://man7.org/linux/man-pages/man2/shmat.2.html).
    shmat = 1073741854,
    /// See doc at [shmctl(2)](https://man7.org/linux/man-pages/man2/shmctl.2.html).
    shmctl = 1073741855,
    /// See doc at [dup(2)](https://man7.org/linux/man-pages/man2/dup.2.html).
    dup = 1073741856,
    /// See doc at [dup2(2)](https://man7.org/linux/man-pages/man2/dup2.2.html).
    dup2 = 1073741857,
    /// See doc at [pause(2)](https://man7.org/linux/man-pages/man2/pause.2.html).
    pause = 1073741858,
    /// See doc at [nanosleep(2)](https://man7.org/linux/man-pages/man2/nanosleep.2.html).
    nanosleep = 1073741859,
    /// See doc at [getitimer(2)](https://man7.org/linux/man-pages/man2/getitimer.2.html).
    getitimer = 1073741860,
    /// See doc at [alarm(2)](https://man7.org/linux/man-pages/man2/alarm.2.html).
    alarm = 1073741861,
    /// See doc at [setitimer(2)](https://man7.org/linux/man-pages/man2/setitimer.2.html).
    setitimer = 1073741862,
    /// See doc at [getpid(2)](https://man7.org/linux/man-pages/man2/getpid.2.html).
    getpid = 1073741863,
    /// See doc at [sendfile(2)](https://man7.org/linux/man-pages/man2/sendfile.2.html).
    sendfile = 1073741864,
    /// See doc at [socket(2)](https://man7.org/linux/man-pages/man2/socket.2.html).
    socket = 1073741865,
    /// See doc at [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html).
    connect = 1073741866,
    /// See doc at [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html).
    accept = 1073741867,
    /// See doc at [sendto(2)](https://man7.org/linux/man-pages/man2/sendto.2.html).
    sendto = 1073741868,
    /// See doc at [shutdown(2)](https://man7.org/linux/man-pages/man2/shutdown.2.html).
    shutdown = 1073741872,
    /// See doc at [bind(2)](https://man7.org/linux/man-pages/man2/bind.2.html).
    bind = 1073741873,
    /// See doc at [listen(2)](https://man7.org/linux/man-pages/man2/listen.2.html).
    listen = 1073741874,
    /// See doc at [getsockname(2)](https://man7.org/linux/man-pages/man2/getsockname.2.html).
    getsockname = 1073741875,
    /// See doc at [getpeername(2)](https://man7.org/linux/man-pages/man2/getpeername.2.html).
    getpeername = 1073741876,
    /// See doc at [socketpair(2)](https://man7.org/linux/man-pages/man2/socketpair.2.html).
    socketpair = 1073741877,
    /// See doc at [clone(2)](https://man7.org/linux/man-pages/man2/clone.2.html).
    clone = 1073741880,
    /// See doc at [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html).
    fork = 1073741881,
    /// See doc at [vfork(2)](https://man7.org/linux/man-pages/man2/vfork.2.html).
    vfork = 1073741882,
    /// See doc at [exit(2)](https://man7.org/linux/man-pages/man2/exit.2.html).
    exit = 1073741884,
    /// See doc at [wait4(2)](https://man7.org/linux/man-pages/man2/wait4.2.html).
    wait4 = 1073741885,
    /// See doc at [kill(2)](https://man7.org/linux/man-pages/man2/kill.2.html).
    kill = 1073741886,
    /// See doc at [uname(2)](https://man7.org/linux/man-pages/man2/uname.2.html).
    uname = 1073741887,
    /// See doc at [semget(2)](https://man7.org/linux/man-pages/man2/semget.2.html).
    semget = 1073741888,
    /// See doc at [semop(2)](https://man7.org/linux/man-pages/man2/semop.2.html).
    semop = 1073741889,
    /// See doc at [semctl(2)](https://man7.org/linux/man-pages/man2/semctl.2.html).
    semctl = 1073741890,
    /// See doc at [shmdt(2)](https://man7.org/linux/man-pages/man2/shmdt.2.html).
    shmdt = 1073741891,
    /// See doc at [msgget(2)](https://man7.org/linux/man-pages/man2/msgget.2.html).
    msgget = 1073741892,
    /// See doc at [msgsnd(2)](https://man7.org/linux/man-pages/man2/msgsnd.2.html).
    msgsnd = 1073741893,
    /// See doc at [msgrcv(2)](https://man7.org/linux/man-pages/man2/msgrcv.2.html).
    msgrcv = 1073741894,
    /// See doc at [msgctl(2)](https://man7.org/linux/man-pages/man2/msgctl.2.html).
    msgctl = 1073741895,
    /// See doc at [fcntl(2)](https://man7.org/linux/man-pages/man2/fcntl.2.html).
    fcntl = 1073741896,
    /// See doc at [flock(2)](https://man7.org/linux/man-pages/man2/flock.2.html).
    flock = 1073741897,
    /// See doc at [fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html).
    fsync = 1073741898,
    /// See doc at [fdatasync(2)](https://man7.org/linux/man-pages/man2/fdatasync.2.html).
    fdatasync = 1073741899,
    /// See doc at [truncate(2)](https://man7.org/linux/man-pages/man2/truncate.2.html).
    truncate = 1073741900,
    /// See doc at [ftruncate(2)](https://man7.org/linux/man-pages/man2/ftruncate.2.html).
    ftruncate = 1073741901,
    /// See doc at [getdents(2)](https://man7.org/linux/man-pages/man2/getdents.2.html).
    getdents = 1073741902,
    /// See doc at [getcwd(2)](https://man7.org/linux/man-pages/man2/getcwd.2.html).
    getcwd = 1073741903,
    /// See doc at [chdir(2)](https://man7.org/linux/man-pages/man2/chdir.2.html).
    chdir = 1073741904,
    /// See doc at [fchdir(2)](https://man7.org/linux/man-pages/man2/fchdir.2.html).
    fchdir = 1073741905,
    /// See doc at [rename(2)](https://man7.org/linux/man-pages/man2/rename.2.html).
    rename = 1073741906,
    /// See doc at [mkdir(2)](https://man7.org/linux/man-pages/man2/mkdir.2.html).
    mkdir = 1073741907,
    /// See doc at [rmdir(2)](https://man7.org/linux/man-pages/man2/rmdir.2.html).
    rmdir = 1073741908,
    /// See doc at [creat(2)](https://man7.org/linux/man-pages/man2/creat.2.html).
    creat = 1073741909,
    /// See doc at [link(2)](https://man7.org/linux/man-pages/man2/link.2.html).
    link = 1073741910,
    /// See doc at [unlink(2)](https://man7.org/linux/man-pages/man2/unlink.2.html).
    unlink = 1073741911,
    /// See doc at [symlink(2)](https://man7.org/linux/man-pages/man2/symlink.2.html).
    symlink = 1073741912,
    /// See doc at [readlink(2)](https://man7.org/linux/man-pages/man2/readlink.2.html).
    readlink = 1073741913,
    /// See doc at [chmod(2)](https://man7.org/linux/man-pages/man2/chmod.2.html).
    chmod = 1073741914,
    /// See doc at [fchmod(2)](https://man7.org/linux/man-pages/man2/fchmod.2.html).
    fchmod = 1073741915,
    /// See doc at [chown(2)](https://man7.org/linux/man-pages/man2/chown.2.html).
    chown = 1073741916,
    /// See doc at [fchown(2)](https://man7.org/linux/man-pages/man2/fchown.2.html).
    fchown = 1073741917,
    /// See doc at [lchown(2)](https://man7.org/linux/man-pages/man2/lchown.2.html).
    lchown = 1073741918,
    /// See doc at [umask(2)](https://man7.org/linux/man-pages/man2/umask.2.html).
    umask = 1073741919,
    /// See doc at [gettimeofday(2)](https://man7.org/linux/man-pages/man2/gettimeofday.2.html).
    gettimeofday = 1073741920,
    /// See doc at [getrlimit(2)](https://man7.org/linux/man-pages/man2/getrlimit.2.html).
    getrlimit = 1073741921,
    /// See doc at [getrusage(2)](https://man7.org/linux/man-pages/man2/getrusage.2.html).
    getrusage = 1073741922,
    /// See doc at [sysinfo(2)](https://man7.org/linux/man-pages/man2/sysinfo.2.html).
    sysinfo = 1073741923,
    /// See doc at [times(2)](https://man7.org/linux/man-pages/man2/times.2.html).
    times = 1073741924,
    /// See doc at [getuid(2)](https://man7.org/linux/man-pages/man2/getuid.2.html).
    getuid = 1073741926,
    /// See doc at [syslog(2)](https://man7.org/linux/man-pages/man2/syslog.2.html).
    syslog = 1073741927,
    /// See doc at [getgid(2)](https://man7.org/linux/man-pages/man2/getgid.2.html).
    getgid = 1073741928,
    /// See doc at [setuid(2)](https://man7.org/linux/man-pages/man2/setuid.2.html).
    setuid = 1073741929,
    /// See doc at [setgid(2)](https://man7.org/linux/man-pages/man2/setgid.2.html).
    setgid = 1073741930,
    /// See doc at [geteuid(2)](https://man7.org/linux/man-pages/man2/geteuid.2.html).
    geteuid = 1073741931,
    /// See doc at [getegid(2)](https://man7.org/linux/man-pages/man2/getegid.2.html).
    getegid = 1073741932,
    /// See doc at [setpgid(2)](https://man7.org/linux/man-pages/man2/setpgid.2.html).
    setpgid = 1073741933,
    /// See doc at [getppid(2)](https://man7.org/linux/man-pages/man2/getppid.2.html).
    getppid = 1073741934,
    /// See doc at [getpgrp(2)](https://man7.org/linux/man-pages/man2/getpgrp.2.html).
    getpgrp = 1073741935,
    /// See doc at [setsid(2)](https://man7.org/linux/man-pages/man2/setsid.2.html).
    setsid = 1073741936,
    /// See doc at [setreuid(2)](https://man7.org/linux/man-pages/man2/setreuid.2.html).
    setreuid = 1073741937,
    /// See doc at [setregid(2)](https://man7.org/linux/man-pages/man2/setregid.2.html).
    setregid = 1073741938,
    /// See doc at [getgroups(2)](https://man7.org/linux/man-pages/man2/getgroups.2.html).
    getgroups = 1073741939,
    /// See doc at [setgroups(2)](https://man7.org/linux/man-pages/man2/setgroups.2.html).
    setgroups = 1073741940,
    /// See doc at [setresuid(2)](https://man7.org/linux/man-pages/man2/setresuid.2.html).
    setresuid = 1073741941,
    /// See doc at [getresuid(2)](https://man7.org/linux/man-pages/man2/getresuid.2.html).
    getresuid = 1073741942,
    /// See doc at [setresgid(2)](https://man7.org/linux/man-pages/man2/setresgid.2.html).
    setresgid = 1073741943,
    /// See doc at [getresgid(2)](https://man7.org/linux/man-pages/man2/getresgid.2.html).
    getresgid = 1073741944,
    /// See doc at [getpgid(2)](https://man7.org/linux/man-pages/man2/getpgid.2.html).
    getpgid = 1073741945,
    /// See doc at [setfsuid(2)](https://man7.org/linux/man-pages/man2/setfsuid.2.html).
    setfsuid = 1073741946,
    /// See doc at [setfsgid(2)](https://man7.org/linux/man-pages/man2/setfsgid.2.html).
    setfsgid = 1073741947,
    /// See doc at [getsid(2)](https://man7.org/linux/man-pages/man2/getsid.2.html).
    getsid = 1073741948,
    /// See doc at [capget(2)](https://man7.org/linux/man-pages/man2/capget.2.html).
    capget = 1073741949,
    /// See doc at [capset(2)](https://man7.org/linux/man-pages/man2/capset.2.html).
    capset = 1073741950,
    /// See doc at [rt_sigsuspend(2)](https://man7.org/linux/man-pages/man2/rt_sigsuspend.2.html).
    rt_sigsuspend = 1073741954,
    /// See doc at [utime(2)](https://man7.org/linux/man-pages/man2/utime.2.html).
    utime = 1073741956,
    /// See doc at [mknod(2)](https://man7.org/linux/man-pages/man2/mknod.2.html).
    mknod = 1073741957,
    /// See doc at [personality(2)](https://man7.org/linux/man-pages/man2/personality.2.html).
    personality = 1073741959,
    /// See doc at [ustat(2)](https://man7.org/linux/man-pages/man2/ustat.2.html).
    ustat = 1073741960,
    /// See doc at [statfs(2)](https://man7.org/linux/man-pages/man2/statfs.2.html).
    statfs = 1073741961,
    /// See doc at [fstatfs(2)](https://man7.org/linux/man-pages/man2/fstatfs.2.html).
    fstatfs = 1073741962,
    /// See doc at [sysfs(2)](https://man7.org/linux/man-pages/man2/sysfs.2.html).
    sysfs = 1073741963,
    /// See doc at [getpriority(2)](https://man7.org/linux/man-pages/man2/getpriority.2.html).
    getpriority = 1073741964,
    /// See doc at [setpriority(2)](https://man7.org/linux/man-pages/man2/setpriority.2.html).
    setpriority = 1073741965,
    /// See doc at [sched_setparam(2)](https://man7.org/linux/man-pages/man2/sched_setparam.2.html).
    sched_setparam = 1073741966,
    /// See doc at [sched_getparam(2)](https://man7.org/linux/man-pages/man2/sched_getparam.2.html).
    sched_getparam = 1073741967,
    /// See doc at [sched_setscheduler(2)](https://man7.org/linux/man-pages/man2/sched_setscheduler.2.html).
    sched_setscheduler = 1073741968,
    /// See doc at [sched_getscheduler(2)](https://man7.org/linux/man-pages/man2/sched_getscheduler.2.html).
    sched_getscheduler = 1073741969,
    /// See doc at [sched_get_priority_max(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_max.2.html).
    sched_get_priority_max = 1073741970,
    /// See doc at [sched_get_priority_min(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_min.2.html).
    sched_get_priority_min = 1073741971,
    /// See doc at [sched_rr_get_interval(2)](https://man7.org/linux/man-pages/man2/sched_rr_get_interval.2.html).
    sched_rr_get_interval = 1073741972,
    /// See doc at [mlock(2)](https://man7.org/linux/man-pages/man2/mlock.2.html).
    mlock = 1073741973,
    /// See doc at [munlock(2)](https://man7.org/linux/man-pages/man2/munlock.2.html).
    munlock = 1073741974,
    /// See doc at [mlockall(2)](https://man7.org/linux/man-pages/man2/mlockall.2.html).
    mlockall = 1073741975,
    /// See doc at [munlockall(2)](https://man7.org/linux/man-pages/man2/munlockall.2.html).
    munlockall = 1073741976,
    /// See doc at [vhangup(2)](https://man7.org/linux/man-pages/man2/vhangup.2.html).
    vhangup = 1073741977,
    /// See doc at [modify_ldt(2)](https://man7.org/linux/man-pages/man2/modify_ldt.2.html).
    modify_ldt = 1073741978,
    /// See doc at [pivot_root(2)](https://man7.org/linux/man-pages/man2/pivot_root.2.html).
    pivot_root = 1073741979,
    /// See doc at [prctl(2)](https://man7.org/linux/man-pages/man2/prctl.2.html).
    prctl = 1073741981,
    /// See doc at [arch_prctl(2)](https://man7.org/linux/man-pages/man2/arch_prctl.2.html).
    arch_prctl = 1073741982,
    /// See doc at [adjtimex(2)](https://man7.org/linux/man-pages/man2/adjtimex.2.html).
    adjtimex = 1073741983,
    /// See doc at [setrlimit(2)](https://man7.org/linux/man-pages/man2/setrlimit.2.html).
    setrlimit = 1073741984,
    /// See doc at [chroot(2)](https://man7.org/linux/man-pages/man2/chroot.2.html).
    chroot = 1073741985,
    /// See doc at [sync(2)](https://man7.org/linux/man-pages/man2/sync.2.html).
    sync = 1073741986,
    /// See doc at [acct(2)](https://man7.org/linux/man-pages/man2/acct.2.html).
    acct = 1073741987,
    /// See doc at [settimeofday(2)](https://man7.org/linux/man-pages/man2/settimeofday.2.html).
    settimeofday = 1073741988,
    /// See doc at [mount(2)](https://man7.org/linux/man-pages/man2/mount.2.html).
    mount = 1073741989,
    /// See doc at [umount2(2)](https://man7.org/linux/man-pages/man2/umount2.2.html).
    umount2 = 1073741990,
    /// See doc at [swapon(2)](https://man7.org/linux/man-pages/man2/swapon.2.html).
    swapon = 1073741991,
    /// See doc at [swapoff(2)](https://man7.org/linux/man-pages/man2/swapoff.2.html).
    swapoff = 1073741992,
    /// See doc at [reboot(2)](https://man7.org/linux/man-pages/man2/reboot.2.html).
    reboot = 1073741993,
    /// See doc at [sethostname(2)](https://man7.org/linux/man-pages/man2/sethostname.2.html).
    sethostname = 1073741994,
    /// See doc at [setdomainname(2)](https://man7.org/linux/man-pages/man2/setdomainname.2.html).
    setdomainname = 1073741995,
    /// See doc at [iopl(2)](https://man7.org/linux/man-pages/man2/iopl.2.html).
    iopl = 1073741996,
    /// See doc at [ioperm(2)](https://man7.org/linux/man-pages/man2/ioperm.2.html).
    ioperm = 1073741997,
    /// See doc at [init_module(2)](https://man7.org/linux/man-pages/man2/init_module.2.html).
    init_module = 1073741999,
    /// See doc at [delete_module(2)](https://man7.org/linux/man-pages/man2/delete_module.2.html).
    delete_module = 1073742000,
    /// See doc at [quotactl(2)](https://man7.org/linux/man-pages/man2/quotactl.2.html).
    quotactl = 1073742003,
    /// See doc at [getpmsg(2)](https://man7.org/linux/man-pages/man2/getpmsg.2.html).
    getpmsg = 1073742005,
    /// See doc at [putpmsg(2)](https://man7.org/linux/man-pages/man2/putpmsg.2.html).
    putpmsg = 1073742006,
    /// See doc at [afs_syscall(2)](https://man7.org/linux/man-pages/man2/afs_syscall.2.html).
    afs_syscall = 1073742007,
    /// See doc at [tuxcall(2)](https://man7.org/linux/man-pages/man2/tuxcall.2.html).
    tuxcall = 1073742008,
    /// See doc at [security(2)](https://man7.org/linux/man-pages/man2/security.2.html).
    security = 1073742009,
    /// See doc at [gettid(2)](https://man7.org/linux/man-pages/man2/gettid.2.html).
    gettid = 1073742010,
    /// See doc at [readahead(2)](https://man7.org/linux/man-pages/man2/readahead.2.html).
    readahead = 1073742011,
    /// See doc at [setxattr(2)](https://man7.org/linux/man-pages/man2/setxattr.2.html).
    setxattr = 1073742012,
    /// See doc at [lsetxattr(2)](https://man7.org/linux/man-pages/man2/lsetxattr.2.html).
    lsetxattr = 1073742013,
    /// See doc at [fsetxattr(2)](https://man7.org/linux/man-pages/man2/fsetxattr.2.html).
    fsetxattr = 1073742014,
    /// See doc at [getxattr(2)](https://man7.org/linux/man-pages/man2/getxattr.2.html).
    getxattr = 1073742015,
    /// See doc at [lgetxattr(2)](https://man7.org/linux/man-pages/man2/lgetxattr.2.html).
    lgetxattr = 1073742016,
    /// See doc at [fgetxattr(2)](https://man7.org/linux/man-pages/man2/fgetxattr.2.html).
    fgetxattr = 1073742017,
    /// See doc at [listxattr(2)](https://man7.org/linux/man-pages/man2/listxattr.2.html).
    listxattr = 1073742018,
    /// See doc at [llistxattr(2)](https://man7.org/linux/man-pages/man2/llistxattr.2.html).
    llistxattr = 1073742019,
    /// See doc at [flistxattr(2)](https://man7.org/linux/man-pages/man2/flistxattr.2.html).
    flistxattr = 1073742020,
    /// See doc at [removexattr(2)](https://man7.org/linux/man-pages/man2/removexattr.2.html).
    removexattr = 1073742021,
    /// See doc at [lremovexattr(2)](https://man7.org/linux/man-pages/man2/lremovexattr.2.html).
    lremovexattr = 1073742022,
    /// See doc at [fremovexattr(2)](https://man7.org/linux/man-pages/man2/fremovexattr.2.html).
    fremovexattr = 1073742023,
    /// See doc at [tkill(2)](https://man7.org/linux/man-pages/man2/tkill.2.html).
    tkill = 1073742024,
    /// See doc at [time(2)](https://man7.org/linux/man-pages/man2/time.2.html).
    time = 1073742025,
    /// See doc at [futex(2)](https://man7.org/linux/man-pages/man2/futex.2.html).
    futex = 1073742026,
    /// See doc at [sched_setaffinity(2)](https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html).
    sched_setaffinity = 1073742027,
    /// See doc at [sched_getaffinity(2)](https://man7.org/linux/man-pages/man2/sched_getaffinity.2.html).
    sched_getaffinity = 1073742028,
    /// See doc at [io_destroy(2)](https://man7.org/linux/man-pages/man2/io_destroy.2.html).
    io_destroy = 1073742031,
    /// See doc at [io_getevents(2)](https://man7.org/linux/man-pages/man2/io_getevents.2.html).
    io_getevents = 1073742032,
    /// See doc at [io_cancel(2)](https://man7.org/linux/man-pages/man2/io_cancel.2.html).
    io_cancel = 1073742034,
    /// See doc at [lookup_dcookie(2)](https://man7.org/linux/man-pages/man2/lookup_dcookie.2.html).
    lookup_dcookie = 1073742036,
    /// See doc at [epoll_create(2)](https://man7.org/linux/man-pages/man2/epoll_create.2.html).
    epoll_create = 1073742037,
    /// See doc at [remap_file_pages(2)](https://man7.org/linux/man-pages/man2/remap_file_pages.2.html).
    remap_file_pages = 1073742040,
    /// See doc at [getdents64(2)](https://man7.org/linux/man-pages/man2/getdents64.2.html).
    getdents64 = 1073742041,
    /// See doc at [set_tid_address(2)](https://man7.org/linux/man-pages/man2/set_tid_address.2.html).
    set_tid_address = 1073742042,
    /// See doc at [restart_syscall(2)](https://man7.org/linux/man-pages/man2/restart_syscall.2.html).
    restart_syscall = 1073742043,
    /// See doc at [semtimedop(2)](https://man7.org/linux/man-pages/man2/semtimedop.2.html).
    semtimedop = 1073742044,
    /// See doc at [fadvise64(2)](https://man7.org/linux/man-pages/man2/fadvise64.2.html).
    fadvise64 = 1073742045,
    /// See doc at [timer_settime(2)](https://man7.org/linux/man-pages/man2/timer_settime.2.html).
    timer_settime = 1073742047,
    /// See doc at [timer_gettime(2)](https://man7.org/linux/man-pages/man2/timer_gettime.2.html).
    timer_gettime = 1073742048,
    /// See doc at [timer_getoverrun(2)](https://man7.org/linux/man-pages/man2/timer_getoverrun.2.html).
    timer_getoverrun = 1073742049,
    /// See doc at [timer_delete(2)](https://man7.org/linux/man-pages/man2/timer_delete.2.html).
    timer_delete = 1073742050,
    /// See doc at [clock_settime(2)](https://man7.org/linux/man-pages/man2/clock_settime.2.html).
    clock_settime = 1073742051,
    /// See doc at [clock_gettime(2)](https://man7.org/linux/man-pages/man2/clock_gettime.2.html).
    clock_gettime = 1073742052,
    /// See doc at [clock_getres(2)](https://man7.org/linux/man-pages/man2/clock_getres.2.html).
    clock_getres = 1073742053,
    /// See doc at [clock_nanosleep(2)](https://man7.org/linux/man-pages/man2/clock_nanosleep.2.html).
    clock_nanosleep = 1073742054,
    /// See doc at [exit_group(2)](https://man7.org/linux/man-pages/man2/exit_group.2.html).
    exit_group = 1073742055,
    /// See doc at [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html).
    epoll_wait = 1073742056,
    /// See doc at [epoll_ctl(2)](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html).
    epoll_ctl = 1073742057,
    /// See doc at [tgkill(2)](https://man7.org/linux/man-pages/man2/tgkill.2.html).
    tgkill = 1073742058,
    /// See doc at [utimes(2)](https://man7.org/linux/man-pages/man2/utimes.2.html).
    utimes = 1073742059,
    /// See doc at [mbind(2)](https://man7.org/linux/man-pages/man2/mbind.2.html).
    mbind = 1073742061,
    /// See doc at [set_mempolicy(2)](https://man7.org/linux/man-pages/man2/set_mempolicy.2.html).
    set_mempolicy = 1073742062,
    /// See doc at [get_mempolicy(2)](https://man7.org/linux/man-pages/man2/get_mempolicy.2.html).
    get_mempolicy = 1073742063,
    /// See doc at [mq_open(2)](https://man7.org/linux/man-pages/man2/mq_open.2.html).
    mq_open = 1073742064,
    /// See doc at [mq_unlink(2)](https://man7.org/linux/man-pages/man2/mq_unlink.2.html).
    mq_unlink = 1073742065,
    /// See doc at [mq_timedsend(2)](https://man7.org/linux/man-pages/man2/mq_timedsend.2.html).
    mq_timedsend = 1073742066,
    /// See doc at [mq_timedreceive(2)](https://man7.org/linux/man-pages/man2/mq_timedreceive.2.html).
    mq_timedreceive = 1073742067,
    /// See doc at [mq_getsetattr(2)](https://man7.org/linux/man-pages/man2/mq_getsetattr.2.html).
    mq_getsetattr = 1073742069,
    /// See doc at [add_key(2)](https://man7.org/linux/man-pages/man2/add_key.2.html).
    add_key = 1073742072,
    /// See doc at [request_key(2)](https://man7.org/linux/man-pages/man2/request_key.2.html).
    request_key = 1073742073,
    /// See doc at [keyctl(2)](https://man7.org/linux/man-pages/man2/keyctl.2.html).
    keyctl = 1073742074,
    /// See doc at [ioprio_set(2)](https://man7.org/linux/man-pages/man2/ioprio_set.2.html).
    ioprio_set = 1073742075,
    /// See doc at [ioprio_get(2)](https://man7.org/linux/man-pages/man2/ioprio_get.2.html).
    ioprio_get = 1073742076,
    /// See doc at [inotify_init(2)](https://man7.org/linux/man-pages/man2/inotify_init.2.html).
    inotify_init = 1073742077,
    /// See doc at [inotify_add_watch(2)](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html).
    inotify_add_watch = 1073742078,
    /// See doc at [inotify_rm_watch(2)](https://man7.org/linux/man-pages/man2/inotify_rm_watch.2.html).
    inotify_rm_watch = 1073742079,
    /// See doc at [migrate_pages(2)](https://man7.org/linux/man-pages/man2/migrate_pages.2.html).
    migrate_pages = 1073742080,
    /// See doc at [openat(2)](https://man7.org/linux/man-pages/man2/openat.2.html).
    openat = 1073742081,
    /// See doc at [mkdirat(2)](https://man7.org/linux/man-pages/man2/mkdirat.2.html).
    mkdirat = 1073742082,
    /// See doc at [mknodat(2)](https://man7.org/linux/man-pages/man2/mknodat.2.html).
    mknodat = 1073742083,
    /// See doc at [fchownat(2)](https://man7.org/linux/man-pages/man2/fchownat.2.html).
    fchownat = 1073742084,
    /// See doc at [futimesat(2)](https://man7.org/linux/man-pages/man2/futimesat.2.html).
    futimesat = 1073742085,
    /// See doc at [newfstatat(2)](https://man7.org/linux/man-pages/man2/newfstatat.2.html).
    newfstatat = 1073742086,
    /// See doc at [unlinkat(2)](https://man7.org/linux/man-pages/man2/unlinkat.2.html).
    unlinkat = 1073742087,
    /// See doc at [renameat(2)](https://man7.org/linux/man-pages/man2/renameat.2.html).
    renameat = 1073742088,
    /// See doc at [linkat(2)](https://man7.org/linux/man-pages/man2/linkat.2.html).
    linkat = 1073742089,
    /// See doc at [symlinkat(2)](https://man7.org/linux/man-pages/man2/symlinkat.2.html).
    symlinkat = 1073742090,
    /// See doc at [readlinkat(2)](https://man7.org/linux/man-pages/man2/readlinkat.2.html).
    readlinkat = 1073742091,
    /// See doc at [fchmodat(2)](https://man7.org/linux/man-pages/man2/fchmodat.2.html).
    fchmodat = 1073742092,
    /// See doc at [faccessat(2)](https://man7.org/linux/man-pages/man2/faccessat.2.html).
    faccessat = 1073742093,
    /// See doc at [pselect6(2)](https://man7.org/linux/man-pages/man2/pselect6.2.html).
    pselect6 = 1073742094,
    /// See doc at [ppoll(2)](https://man7.org/linux/man-pages/man2/ppoll.2.html).
    ppoll = 1073742095,
    /// See doc at [unshare(2)](https://man7.org/linux/man-pages/man2/unshare.2.html).
    unshare = 1073742096,
    /// See doc at [splice(2)](https://man7.org/linux/man-pages/man2/splice.2.html).
    splice = 1073742099,
    /// See doc at [tee(2)](https://man7.org/linux/man-pages/man2/tee.2.html).
    tee = 1073742100,
    /// See doc at [sync_file_range(2)](https://man7.org/linux/man-pages/man2/sync_file_range.2.html).
    sync_file_range = 1073742101,
    /// See doc at [utimensat(2)](https://man7.org/linux/man-pages/man2/utimensat.2.html).
    utimensat = 1073742104,
    /// See doc at [epoll_pwait(2)](https://man7.org/linux/man-pages/man2/epoll_pwait.2.html).
    epoll_pwait = 1073742105,
    /// See doc at [signalfd(2)](https://man7.org/linux/man-pages/man2/signalfd.2.html).
    signalfd = 1073742106,
    /// See doc at [timerfd_create(2)](https://man7.org/linux/man-pages/man2/timerfd_create.2.html).
    timerfd_create = 1073742107,
    /// See doc at [eventfd(2)](https://man7.org/linux/man-pages/man2/eventfd.2.html).
    eventfd = 1073742108,
    /// See doc at [fallocate(2)](https://man7.org/linux/man-pages/man2/fallocate.2.html).
    fallocate = 1073742109,
    /// See doc at [timerfd_settime(2)](https://man7.org/linux/man-pages/man2/timerfd_settime.2.html).
    timerfd_settime = 1073742110,
    /// See doc at [timerfd_gettime(2)](https://man7.org/linux/man-pages/man2/timerfd_gettime.2.html).
    timerfd_gettime = 1073742111,
    /// See doc at [accept4(2)](https://man7.org/linux/man-pages/man2/accept4.2.html).
    accept4 = 1073742112,
    /// See doc at [signalfd4(2)](https://man7.org/linux/man-pages/man2/signalfd4.2.html).
    signalfd4 = 1073742113,
    /// See doc at [eventfd2(2)](https://man7.org/linux/man-pages/man2/eventfd2.2.html).
    eventfd2 = 1073742114,
    /// See doc at [epoll_create1(2)](https://man7.org/linux/man-pages/man2/epoll_create1.2.html).
    epoll_create1 = 1073742115,
    /// See doc at [dup3(2)](https://man7.org/linux/man-pages/man2/dup3.2.html).
    dup3 = 1073742116,
    /// See doc at [pipe2(2)](https://man7.org/linux/man-pages/man2/pipe2.2.html).
    pipe2 = 1073742117,
    /// See doc at [inotify_init1(2)](https://man7.org/linux/man-pages/man2/inotify_init1.2.html).
    inotify_init1 = 1073742118,
    /// See doc at [perf_event_open(2)](https://man7.org/linux/man-pages/man2/perf_event_open.2.html).
    perf_event_open = 1073742122,
    /// See doc at [fanotify_init(2)](https://man7.org/linux/man-pages/man2/fanotify_init.2.html).
    fanotify_init = 1073742124,
    /// See doc at [fanotify_mark(2)](https://man7.org/linux/man-pages/man2/fanotify_mark.2.html).
    fanotify_mark = 1073742125,
    /// See doc at [prlimit64(2)](https://man7.org/linux/man-pages/man2/prlimit64.2.html).
    prlimit64 = 1073742126,
    /// See doc at [name_to_handle_at(2)](https://man7.org/linux/man-pages/man2/name_to_handle_at.2.html).
    name_to_handle_at = 1073742127,
    /// See doc at [open_by_handle_at(2)](https://man7.org/linux/man-pages/man2/open_by_handle_at.2.html).
    open_by_handle_at = 1073742128,
    /// See doc at [clock_adjtime(2)](https://man7.org/linux/man-pages/man2/clock_adjtime.2.html).
    clock_adjtime = 1073742129,
    /// See doc at [syncfs(2)](https://man7.org/linux/man-pages/man2/syncfs.2.html).
    syncfs = 1073742130,
    /// See doc at [setns(2)](https://man7.org/linux/man-pages/man2/setns.2.html).
    setns = 1073742132,
    /// See doc at [getcpu(2)](https://man7.org/linux/man-pages/man2/getcpu.2.html).
    getcpu = 1073742133,
    /// See doc at [kcmp(2)](https://man7.org/linux/man-pages/man2/kcmp.2.html).
    kcmp = 1073742136,
    /// See doc at [finit_module(2)](https://man7.org/linux/man-pages/man2/finit_module.2.html).
    finit_module = 1073742137,
    /// See doc at [sched_setattr(2)](https://man7.org/linux/man-pages/man2/sched_setattr.2.html).
    sched_setattr = 1073742138,
    /// See doc at [sched_getattr(2)](https://man7.org/linux/man-pages/man2/sched_getattr.2.html).
    sched_getattr = 1073742139,
    /// See doc at [renameat2(2)](https://man7.org/linux/man-pages/man2/renameat2.2.html).
    renameat2 = 1073742140,
    /// See doc at [seccomp(2)](https://man7.org/linux/man-pages/man2/seccomp.2.html).
    seccomp = 1073742141,
    /// See doc at [getrandom(2)](https://man7.org/linux/man-pages/man2/getrandom.2.html).
    getrandom = 1073742142,
    /// See doc at [memfd_create(2)](https://man7.org/linux/man-pages/man2/memfd_create.2.html).
    memfd_create = 1073742143,
    /// See doc at [kexec_file_load(2)](https://man7.org/linux/man-pages/man2/kexec_file_load.2.html).
    kexec_file_load = 1073742144,
    /// See doc at [bpf(2)](https://man7.org/linux/man-pages/man2/bpf.2.html).
    bpf = 1073742145,
    /// See doc at [userfaultfd(2)](https://man7.org/linux/man-pages/man2/userfaultfd.2.html).
    userfaultfd = 1073742147,
    /// See doc at [membarrier(2)](https://man7.org/linux/man-pages/man2/membarrier.2.html).
    membarrier = 1073742148,
    /// See doc at [mlock2(2)](https://man7.org/linux/man-pages/man2/mlock2.2.html).
    mlock2 = 1073742149,
    /// See doc at [copy_file_range(2)](https://man7.org/linux/man-pages/man2/copy_file_range.2.html).
    copy_file_range = 1073742150,
    /// See doc at [pkey_mprotect(2)](https://man7.org/linux/man-pages/man2/pkey_mprotect.2.html).
    pkey_mprotect = 1073742153,
    /// See doc at [pkey_alloc(2)](https://man7.org/linux/man-pages/man2/pkey_alloc.2.html).
    pkey_alloc = 1073742154,
    /// See doc at [pkey_free(2)](https://man7.org/linux/man-pages/man2/pkey_free.2.html).
    pkey_free = 1073742155,
    /// See doc at [statx(2)](https://man7.org/linux/man-pages/man2/statx.2.html).
    statx = 1073742156,
    /// See doc at [io_pgetevents(2)](https://man7.org/linux/man-pages/man2/io_pgetevents.2.html).
    io_pgetevents = 1073742157,
    /// See doc at [rseq(2)](https://man7.org/linux/man-pages/man2/rseq.2.html).
    rseq = 1073742158,
    /// See doc at [pidfd_send_signal(2)](https://man7.org/linux/man-pages/man2/pidfd_send_signal.2.html).
    pidfd_send_signal = 1073742248,
    /// See doc at [io_uring_setup(2)](https://man7.org/linux/man-pages/man2/io_uring_setup.2.html).
    io_uring_setup = 1073742249,
    /// See doc at [io_uring_enter(2)](https://man7.org/linux/man-pages/man2/io_uring_enter.2.html).
    io_uring_enter = 1073742250,
    /// See doc at [io_uring_register(2)](https://man7.org/linux/man-pages/man2/io_uring_register.2.html).
    io_uring_register = 1073742251,
    /// See doc at [open_tree(2)](https://man7.org/linux/man-pages/man2/open_tree.2.html).
    open_tree = 1073742252,
    /// See doc at [move_mount(2)](https://man7.org/linux/man-pages/man2/move_mount.2.html).
    move_mount = 1073742253,
    /// See doc at [fsopen(2)](https://man7.org/linux/man-pages/man2/fsopen.2.html).
    fsopen = 1073742254,
    /// See doc at [fsconfig(2)](https://man7.org/linux/man-pages/man2/fsconfig.2.html).
    fsconfig = 1073742255,
    /// See doc at [fsmount(2)](https://man7.org/linux/man-pages/man2/fsmount.2.html).
    fsmount = 1073742256,
    /// See doc at [fspick(2)](https://man7.org/linux/man-pages/man2/fspick.2.html).
    fspick = 1073742257,
    /// See doc at [pidfd_open(2)](https://man7.org/linux/man-pages/man2/pidfd_open.2.html).
    pidfd_open = 1073742258,
    /// See doc at [clone3(2)](https://man7.org/linux/man-pages/man2/clone3.2.html).
    clone3 = 1073742259,
    /// See doc at [close_range(2)](https://man7.org/linux/man-pages/man2/close_range.2.html).
    close_range = 1073742260,
    /// See doc at [openat2(2)](https://man7.org/linux/man-pages/man2/openat2.2.html).
    openat2 = 1073742261,
    /// See doc at [pidfd_getfd(2)](https://man7.org/linux/man-pages/man2/pidfd_getfd.2.html).
    pidfd_getfd = 1073742262,
    /// See doc at [faccessat2(2)](https://man7.org/linux/man-pages/man2/faccessat2.2.html).
    faccessat2 = 1073742263,
    /// See doc at [process_madvise(2)](https://man7.org/linux/man-pages/man2/process_madvise.2.html).
    process_madvise = 1073742264,
    /// See doc at [epoll_pwait2(2)](https://man7.org/linux/man-pages/man2/epoll_pwait2.2.html).
    epoll_pwait2 = 1073742265,
    /// See doc at [mount_setattr(2)](https://man7.org/linux/man-pages/man2/mount_setattr.2.html).
    mount_setattr = 1073742266,
    /// See doc at [quotactl_fd(2)](https://man7.org/linux/man-pages/man2/quotactl_fd.2.html).
    quotactl_fd = 1073742267,
    /// See doc at [landlock_create_ruleset(2)](https://man7.org/linux/man-pages/man2/landlock_create_ruleset.2.html).
    landlock_create_ruleset = 1073742268,
    /// See doc at [landlock_add_rule(2)](https://man7.org/linux/man-pages/man2/landlock_add_rule.2.html).
    landlock_add_rule = 1073742269,
    /// See doc at [landlock_restrict_self(2)](https://man7.org/linux/man-pages/man2/landlock_restrict_self.2.html).
    landlock_restrict_self = 1073742270,
    /// See doc at [memfd_secret(2)](https://man7.org/linux/man-pages/man2/memfd_secret.2.html).
    memfd_secret = 1073742271,
    /// See doc at [process_mrelease(2)](https://man7.org/linux/man-pages/man2/process_mrelease.2.html).
    process_mrelease = 1073742272,
    /// See doc at [futex_waitv(2)](https://man7.org/linux/man-pages/man2/futex_waitv.2.html).
    futex_waitv = 1073742273,
    /// See doc at [set_mempolicy_home_node(2)](https://man7.org/linux/man-pages/man2/set_mempolicy_home_node.2.html).
    set_mempolicy_home_node = 1073742274,
    /// See doc at [cachestat(2)](https://man7.org/linux/man-pages/man2/cachestat.2.html).
    cachestat = 1073742275,
    /// See doc at [fchmodat2(2)](https://man7.org/linux/man-pages/man2/fchmodat2.2.html).
    fchmodat2 = 1073742276,
    /// See doc at [futex_wake(2)](https://man7.org/linux/man-pages/man2/futex_wake.2.html).
    futex_wake = 1073742278,
    /// See doc at [futex_wait(2)](https://man7.org/linux/man-pages/man2/futex_wait.2.html).
    futex_wait = 1073742279,
    /// See doc at [futex_requeue(2)](https://man7.org/linux/man-pages/man2/futex_requeue.2.html).
    futex_requeue = 1073742280,
    /// See doc at [statmount(2)](https://man7.org/linux/man-pages/man2/statmount.2.html).
    statmount = 1073742281,
    /// See doc at [listmount(2)](https://man7.org/linux/man-pages/man2/listmount.2.html).
    listmount = 1073742282,
    /// See doc at [lsm_get_self_attr(2)](https://man7.org/linux/man-pages/man2/lsm_get_self_attr.2.html).
    lsm_get_self_attr = 1073742283,
    /// See doc at [lsm_set_self_attr(2)](https://man7.org/linux/man-pages/man2/lsm_set_self_attr.2.html).
    lsm_set_self_attr = 1073742284,
    /// See doc at [lsm_list_modules(2)](https://man7.org/linux/man-pages/man2/lsm_list_modules.2.html).
    lsm_list_modules = 1073742285,
    /// See doc at [rt_sigaction(2)](https://man7.org/linux/man-pages/man2/rt_sigaction.2.html).
    rt_sigaction = 1073742336,
    /// See doc at [rt_sigreturn(2)](https://man7.org/linux/man-pages/man2/rt_sigreturn.2.html).
    rt_sigreturn = 1073742337,
    /// See doc at [ioctl(2)](https://man7.org/linux/man-pages/man2/ioctl.2.html).
    ioctl = 1073742338,
    /// See doc at [readv(2)](https://man7.org/linux/man-pages/man2/readv.2.html).
    readv = 1073742339,
    /// See doc at [writev(2)](https://man7.org/linux/man-pages/man2/writev.2.html).
    writev = 1073742340,
    /// See doc at [recvfrom(2)](https://man7.org/linux/man-pages/man2/recvfrom.2.html).
    recvfrom = 1073742341,
    /// See doc at [sendmsg(2)](https://man7.org/linux/man-pages/man2/sendmsg.2.html).
    sendmsg = 1073742342,
    /// See doc at [recvmsg(2)](https://man7.org/linux/man-pages/man2/recvmsg.2.html).
    recvmsg = 1073742343,
    /// See doc at [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html).
    execve = 1073742344,
    /// See doc at [ptrace(2)](https://man7.org/linux/man-pages/man2/ptrace.2.html).
    ptrace = 1073742345,
    /// See doc at [rt_sigpending(2)](https://man7.org/linux/man-pages/man2/rt_sigpending.2.html).
    rt_sigpending = 1073742346,
    /// See doc at [rt_sigtimedwait(2)](https://man7.org/linux/man-pages/man2/rt_sigtimedwait.2.html).
    rt_sigtimedwait = 1073742347,
    /// See doc at [rt_sigqueueinfo(2)](https://man7.org/linux/man-pages/man2/rt_sigqueueinfo.2.html).
    rt_sigqueueinfo = 1073742348,
    /// See doc at [sigaltstack(2)](https://man7.org/linux/man-pages/man2/sigaltstack.2.html).
    sigaltstack = 1073742349,
    /// See doc at [timer_create(2)](https://man7.org/linux/man-pages/man2/timer_create.2.html).
    timer_create = 1073742350,
    /// See doc at [mq_notify(2)](https://man7.org/linux/man-pages/man2/mq_notify.2.html).
    mq_notify = 1073742351,
    /// See doc at [kexec_load(2)](https://man7.org/linux/man-pages/man2/kexec_load.2.html).
    kexec_load = 1073742352,
    /// See doc at [waitid(2)](https://man7.org/linux/man-pages/man2/waitid.2.html).
    waitid = 1073742353,
    /// See doc at [set_robust_list(2)](https://man7.org/linux/man-pages/man2/set_robust_list.2.html).
    set_robust_list = 1073742354,
    /// See doc at [get_robust_list(2)](https://man7.org/linux/man-pages/man2/get_robust_list.2.html).
    get_robust_list = 1073742355,
    /// See doc at [vmsplice(2)](https://man7.org/linux/man-pages/man2/vmsplice.2.html).
    vmsplice = 1073742356,
    /// See doc at [move_pages(2)](https://man7.org/linux/man-pages/man2/move_pages.2.html).
    move_pages = 1073742357,
    /// See doc at [preadv(2)](https://man7.org/linux/man-pages/man2/preadv.2.html).
    preadv = 1073742358,
    /// See doc at [pwritev(2)](https://man7.org/linux/man-pages/man2/pwritev.2.html).
    pwritev = 1073742359,
    /// See doc at [rt_tgsigqueueinfo(2)](https://man7.org/linux/man-pages/man2/rt_tgsigqueueinfo.2.html).
    rt_tgsigqueueinfo = 1073742360,
    /// See doc at [recvmmsg(2)](https://man7.org/linux/man-pages/man2/recvmmsg.2.html).
    recvmmsg = 1073742361,
    /// See doc at [sendmmsg(2)](https://man7.org/linux/man-pages/man2/sendmmsg.2.html).
    sendmmsg = 1073742362,
    /// See doc at [process_vm_readv(2)](https://man7.org/linux/man-pages/man2/process_vm_readv.2.html).
    process_vm_readv = 1073742363,
    /// See doc at [process_vm_writev(2)](https://man7.org/linux/man-pages/man2/process_vm_writev.2.html).
    process_vm_writev = 1073742364,
    /// See doc at [setsockopt(2)](https://man7.org/linux/man-pages/man2/setsockopt.2.html).
    setsockopt = 1073742365,
    /// See doc at [getsockopt(2)](https://man7.org/linux/man-pages/man2/getsockopt.2.html).
    getsockopt = 1073742366,
    /// See doc at [io_setup(2)](https://man7.org/linux/man-pages/man2/io_setup.2.html).
    io_setup = 1073742367,
    /// See doc at [io_submit(2)](https://man7.org/linux/man-pages/man2/io_submit.2.html).
    io_submit = 1073742368,
    /// See doc at [execveat(2)](https://man7.org/linux/man-pages/man2/execveat.2.html).
    execveat = 1073742369,
    /// See doc at [preadv2(2)](https://man7.org/linux/man-pages/man2/preadv2.2.html).
    preadv2 = 1073742370,
    /// See doc at [pwritev2(2)](https://man7.org/linux/man-pages/man2/pwritev2.2.html).
    pwritev2 = 1073742371,
}
